# NEET Physics & Chemistry Question Bank — Production Grade
# NEET Physics: ~350 questions across 28 chapters
# NEET Chemistry: ~260 questions across 26 chapters (shares with JEE for inorganic/physical)

# ═══════════════════════════════════════════════════════════════════════════════
#  NEET PHYSICS BANK
# ═══════════════════════════════════════════════════════════════════════════════
NEET_PHYSICS_BANK = {

    ("Physics", "Units, Dimensions & Measurement"): {
        "subtopics": ["Dimensional Analysis", "Error Analysis", "Significant Figures"],
        "questions": [
            dict(subtopic="Dimensional Analysis", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="The dimensional formula of pressure is:",
                 options=["[MLT⁻²]", "[ML⁻¹T⁻²]", "[ML²T⁻²]", "[M⁰LT⁻¹]"],
                 answer="B",
                 solution="Pressure = Force/Area = [MLT⁻²]/[L²] = [ML⁻¹T⁻²].",
                 tags=["neet", "ncert_direct", "dimensional_analysis"]),
            dict(subtopic="Dimensional Analysis", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="The unit of surface tension in SI system is:",
                 options=["N/m²", "N/m", "N·m", "N·m²"],
                 answer="B",
                 solution="Surface tension = Force/Length. Unit = N/m.",
                 tags=["neet", "ncert_direct", "units"]),
            dict(subtopic="Error Analysis", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="If A = πr², and error in r is 2%, the error in A is:",
                 options=["2%", "1%", "4%", "8%"],
                 answer="C",
                 solution="ΔA/A = 2(Δr/r) = 2×2% = 4%.",
                 tags=["neet", "error_analysis"]),
            dict(subtopic="Significant Figures", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Number of significant figures in 0.00823 is:",
                 options=["5", "6", "3", "4"],
                 answer="C",
                 solution="Leading zeros are not significant. Significant figures: 8, 2, 3 — total 3.",
                 tags=["neet", "ncert_direct", "significant_figures"]),
            dict(subtopic="Dimensional Analysis", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The physical quantity having the same dimensions as Planck's constant h is:",
                 options=["Linear momentum", "Angular momentum", "Energy", "Force"],
                 answer="B",
                 solution="[h] = J·s = kg·m²·s⁻¹ = [ML²T⁻¹]. Angular momentum = mvr = [M][LT⁻¹][L] = [ML²T⁻¹]. Same dimensions.",
                 tags=["neet", "dimensional_analysis"]),
            dict(subtopic="Error Analysis", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="A resistance R = V/I where V = (100±5)V and I = (10±0.2)A. The percentage error in R is:",
                 options=["5%", "7%", "2%", "3%"],
                 answer="B",
                 solution="ΔR/R = ΔV/V + ΔI/I = 5/100 + 0.2/10 = 0.05+0.02 = 0.07 = 7%.",
                 tags=["neet", "error_analysis"]),
        ]
    },

    ("Physics", "Motion in a Straight Line"): {
        "subtopics": ["Uniform Motion", "Acceleration", "Graphs"],
        "questions": [
            dict(subtopic="Uniform Motion", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="A car travels 100 km in 2 hours. Its average speed is:",
                 options=["50 km/h", "100 km/h", "200 km/h", "25 km/h"],
                 answer="A",
                 solution="Average speed = total distance/total time = 100/2 = 50 km/h.",
                 tags=["neet", "ncert_direct", "average_speed"]),
            dict(subtopic="Acceleration", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="A body starts from rest and accelerates uniformly at 2 m/s². Velocity after 5 seconds is:",
                 options=["10 m/s", "5 m/s", "2 m/s", "20 m/s"],
                 answer="A",
                 solution="v = u + at = 0 + 2×5 = 10 m/s.",
                 tags=["neet", "ncert_direct", "kinematics"]),
            dict(subtopic="Acceleration", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="A ball is dropped from a height of 20 m. Time to reach ground (g=10 m/s²):",
                 options=["1 s", "2 s", "4 s", "√2 s"],
                 answer="B",
                 solution="h = ½gt² → 20 = ½(10)t² → t² = 4 → t = 2 s.",
                 tags=["neet", "ncert_direct", "free_fall"]),
            dict(subtopic="Graphs", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The area under velocity-time graph represents:",
                 options=["Acceleration", "Displacement", "Speed", "Jerk"],
                 answer="B",
                 solution="Area under v-t graph = ∫v dt = displacement.",
                 tags=["neet", "v_t_graph"]),
            dict(subtopic="Acceleration", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="A body moves with initial velocity 10 m/s and acceleration -2 m/s². It stops after:",
                 options=["5 s", "10 s", "20 s", "2 s"],
                 answer="A",
                 solution="v = u + at → 0 = 10 + (-2)t → t = 5 s.",
                 tags=["neet", "retardation"]),
            dict(subtopic="Graphs", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="A particle starts from rest and moves with acceleration a = (4t-2) m/s². Velocity at t=3s is:",
                 options=["12 m/s", "6 m/s", "24 m/s", "30 m/s"],
                 answer="A",
                 solution="v = ∫₀³(4t-2)dt = [2t²-2t]₀³ = 18-6 = 12 m/s.",
                 tags=["neet", "variable_acceleration"]),
        ]
    },

    ("Physics", "Motion in a Plane"): {
        "subtopics": ["Projectile Motion", "Circular Motion", "Relative Velocity"],
        "questions": [
            dict(subtopic="Projectile Motion", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="A projectile is thrown at 45° to horizontal. The ratio of horizontal to vertical components of initial velocity is:",
                 options=["1:1", "√2:1", "1:√2", "2:1"],
                 answer="A",
                 solution="At 45°: Vₓ = Vcosθ = Vcos45° = V/√2. Vᵧ = Vsinθ = V/√2. Ratio = 1:1.",
                 tags=["neet", "ncert_direct", "projectile"]),
            dict(subtopic="Projectile Motion", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="Maximum range of a projectile is R. Maximum height achieved is:",
                 options=["R/4", "R/2", "2R", "R"],
                 answer="A",
                 solution="At θ=45° for max range: R = u²/g. Maximum height H = u²sin²45°/2g = u²/(2×2g) = R/4.",
                 tags=["neet", "ncert_direct", "projectile_range"]),
            dict(subtopic="Circular Motion", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="A body moves in a circle of radius 2 m with speed 4 m/s. Centripetal acceleration is:",
                 options=["4 m/s²", "8 m/s²", "16 m/s²", "2 m/s²"],
                 answer="B",
                 solution="aс = v²/r = 16/2 = 8 m/s².",
                 tags=["neet", "centripetal_acceleration"]),
            dict(subtopic="Relative Velocity", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Rain falls vertically at 20 m/s. A man walks east at 20 m/s. Relative velocity of rain with respect to man is:",
                 options=["0", "20√2 m/s at 45° west of vertical", "40 m/s", "20 m/s"],
                 answer="B",
                 solution="V_rain relative to man = V_rain - V_man = (0,-20) - (20,0) = (-20,-20). |V_rel| = 20√2 m/s at 45°.",
                 tags=["neet", "relative_velocity"]),
        ]
    },

    ("Physics", "Laws of Motion"): {
        "subtopics": ["Newton's Laws", "Friction", "Pseudo Force"],
        "questions": [
            dict(subtopic="Newton's Laws", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="According to Newton's 3rd law, when a horse pulls a cart, the reaction force acts on:",
                 options=["The ground", "The horse", "The air", "The cart"],
                 answer="B",
                 solution="By Newton's 3rd law, if horse (action) pulls cart forward, then cart (reaction) pulls horse backward. The reaction acts on the horse.",
                 tags=["neet", "ncert_direct", "newtons_third_law"]),
            dict(subtopic="Newton's Laws", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="A force of 10 N acts on a mass of 2 kg. The acceleration produced is:",
                 options=["20 m/s²", "0.2 m/s²", "5 m/s²", "12 m/s²"],
                 answer="C",
                 solution="F = ma → a = F/m = 10/2 = 5 m/s².",
                 tags=["neet", "ncert_direct", "newtons_second_law"]),
            dict(subtopic="Friction", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="A body of mass 10 kg rests on a surface with μ = 0.3. Normal force is 100 N. Force of friction is:",
                 options=["30 N", "3 N", "10 N", "100 N"],
                 answer="A",
                 solution="f = μN = 0.3 × 100 = 30 N.",
                 tags=["neet", "ncert_direct", "friction"]),
            dict(subtopic="Friction", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="A block slides down an inclined plane of angle 30°. Coefficient of kinetic friction = 0.3. Acceleration (g=10 m/s²) is:",
                 options=["2.4 m/s²", "5 m/s²", "7.4 m/s²", "2.6 m/s²"],
                 answer="A",
                 solution="a = g(sinθ - μcosθ) = 10(sin30° - 0.3cos30°) = 10(0.5 - 0.3×0.866) = 10(0.5-0.26) = 2.4 m/s².",
                 tags=["neet", "inclined_plane_friction"]),
            dict(subtopic="Pseudo Force", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="A pendulum is in a train accelerating at 5 m/s². Angle of inclination from vertical is: (g=10)",
                 options=["tan⁻¹(0.5)", "45°", "30°", "60°"],
                 answer="A",
                 solution="tanθ = a/g = 5/10 = 0.5. θ = tan⁻¹(0.5) ≈ 26.6°.",
                 tags=["neet", "pseudo_force"]),
        ]
    },

    ("Physics", "Work, Energy & Power"): {
        "subtopics": ["Work Done", "KE PE", "Conservation", "Power"],
        "questions": [
            dict(subtopic="Work Done", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Work done by a force of 10 N in displacing a body 5 m in the direction of force is:",
                 options=["50 J", "2 J", "15 J", "0 J"],
                 answer="A",
                 solution="W = F·d·cosθ = 10×5×cos0° = 50 J.",
                 tags=["neet", "ncert_direct", "work"]),
            dict(subtopic="KE PE", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="KE of a body of mass 2 kg moving at 3 m/s is:",
                 options=["6 J", "9 J", "3 J", "18 J"],
                 answer="B",
                 solution="KE = ½mv² = ½×2×9 = 9 J.",
                 tags=["neet", "ncert_direct", "kinetic_energy"]),
            dict(subtopic="Conservation", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="A ball of mass 1 kg falls from a height 10 m. Its velocity just before hitting the ground is: (g=10)",
                 options=["10 m/s", "100 m/s", "14.1 m/s", "20 m/s"],
                 answer="C",
                 solution="By energy conservation: mgh = ½mv². v = √(2gh) = √(2×10×10) = √200 = 10√2 ≈ 14.1 m/s.",
                 tags=["neet", "energy_conservation"]),
            dict(subtopic="Power", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="A pump lifts 1000 litres of water per minute to a height of 10 m. Power of pump (g=10) is:",
                 options=["1666 W", "100 W", "1000 W", "6000 W"],
                 answer="A",
                 solution="Mass per minute = 1000 kg. Energy per min = mgh = 1000×10×10 = 100000 J/min. Power = 100000/60 ≈ 1666 W.",
                 tags=["neet", "power"]),
        ]
    },

    ("Physics", "System of Particles & Rotational Motion"): {
        "subtopics": ["COM", "Rotational KE", "Moment of Inertia", "Rolling"],
        "questions": [
            dict(subtopic="Moment of Inertia", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Moment of inertia of a disc about its axis is I = MR²/2. For a ring of same mass M and radius R, it is:",
                 options=["MR²", "MR²/2", "2MR²", "MR²/4"],
                 answer="A",
                 solution="Moment of inertia of a ring (thin hoop) about its axis = MR².",
                 tags=["neet", "ncert_direct", "moment_of_inertia"]),
            dict(subtopic="COM", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.76,
                 q_type="single_correct",
                 text="Centre of mass of two equal masses m separated by distance d is at:",
                 options=["d/4 from either mass", "d/2 from each mass", "d/3 from lighter mass", "d from one mass"],
                 answer="B",
                 solution="COM = (m×0 + m×d)/(m+m) = d/2. Located at the midpoint.",
                 tags=["neet", "ncert_direct", "centre_of_mass"]),
            dict(subtopic="Rolling", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="A solid sphere rolls down without slipping. Ratio of rotational KE to total KE is:",
                 options=["2/7", "5/7", "2/5", "1/2"],
                 answer="A",
                 solution="Total KE = ½mv² + ½Iω² = ½mv² + ½(2/5 mr²)(v/r)² = ½mv²(1+2/5) = 7mv²/10. Rotational KE = (1/5)mv². Ratio = (mv²/5)/(7mv²/10) = 2/7.",
                 tags=["neet", "rolling_without_slipping"]),
        ]
    },

    ("Physics", "Gravitation"): {
        "subtopics": ["Kepler's Laws", "Gravitational Potential", "Satellites"],
        "questions": [
            dict(subtopic="Kepler's Laws", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Kepler's second law (equal areas in equal time) is a consequence of:",
                 options=["Conservation of energy", "Conservation of angular momentum", "Conservation of linear momentum", "Newton's third law"],
                 answer="B",
                 solution="Kepler's 2nd law (areal velocity = constant) is a direct consequence of conservation of angular momentum, since no torque acts on the planet.",
                 tags=["neet", "ncert_direct", "kepler"]),
            dict(subtopic="Satellites", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="Escape velocity from Earth's surface is approximately:",
                 options=["7.9 km/s", "11.2 km/s", "3 km/s", "30 km/s"],
                 answer="B",
                 solution="Escape velocity = √(2gR) = √(2×9.8×6.4×10⁶) ≈ 11.2 km/s.",
                 tags=["neet", "ncert_direct", "escape_velocity"]),
            dict(subtopic="Gravitational Potential", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Gravitational potential energy of a body of mass m at height h (h<<R) above Earth's surface is:",
                 options=["mgh", "-mgh", "mgR", "-mgR"],
                 answer="A",
                 solution="For h<<R, increase in PE = mgh (taking Earth's surface as reference). The absolute PE is negative but the increase from the surface is +mgh.",
                 tags=["neet", "gravitational_pe"]),
        ]
    },

    ("Physics", "Mechanical Properties of Solids"): {
        "subtopics": ["Stress Strain", "Elastic Moduli", "Poisson's Ratio"],
        "questions": [
            dict(subtopic="Elastic Moduli", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Young's modulus is defined as:",
                 options=["Volumetric stress/Volumetric strain", "Longitudinal stress/Longitudinal strain", "Shear stress/Shear strain", "Pressure/Volume"],
                 answer="B",
                 solution="Young's modulus Y = Longitudinal (tensile/compressive) stress / Longitudinal strain.",
                 tags=["neet", "ncert_direct", "young_modulus"]),
            dict(subtopic="Stress Strain", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="A wire of area 2×10⁻⁶ m² is stretched by a force of 100 N. The stress is:",
                 options=["5×10⁷ Pa", "2×10⁻⁸ Pa", "200 Pa", "5×10⁴ Pa"],
                 answer="A",
                 solution="Stress = F/A = 100/(2×10⁻⁶) = 5×10⁷ Pa.",
                 tags=["neet", "stress"]),
        ]
    },

    ("Physics", "Mechanical Properties of Fluids"): {
        "subtopics": ["Pressure", "Bernoulli", "Viscosity", "Surface Tension"],
        "questions": [
            dict(subtopic="Pressure", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Pressure at a depth h in a liquid of density ρ (atmospheric pressure P₀) is:",
                 options=["P₀ + ρgh", "ρgh", "P₀ - ρgh", "ρgh - P₀"],
                 answer="A",
                 solution="P = P₀ + ρgh. The total pressure at depth h includes atmospheric + hydrostatic pressure.",
                 tags=["neet", "ncert_direct", "hydrostatic_pressure"]),
            dict(subtopic="Bernoulli", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Bernoulli's principle is based on conservation of:",
                 options=["Mass", "Energy", "Momentum", "Volume"],
                 answer="B",
                 solution="Bernoulli's equation is derived from conservation of energy for flowing fluids (work-energy theorem applied to fluid flow).",
                 tags=["neet", "bernoulli"]),
            dict(subtopic="Surface Tension", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Capillary rise in a tube of radius r is h = 2T cosθ/ρgr. If tube radius is halved, rise becomes:",
                 options=["Same", "Halved", "Doubled", "Quadrupled"],
                 answer="C",
                 solution="h ∝ 1/r. If r is halved (r/2), h becomes 2h (doubled).",
                 tags=["neet", "capillary_rise"]),
        ]
    },

    ("Physics", "Thermal Properties of Matter"): {
        "subtopics": ["Specific Heat", "Latent Heat", "Conduction Convection Radiation"],
        "questions": [
            dict(subtopic="Specific Heat", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Heat required to raise temperature of 500 g of water from 20°C to 80°C (specific heat = 4200 J/kg·K) is:",
                 options=["126 kJ", "12.6 kJ", "252 kJ", "63 kJ"],
                 answer="A",
                 solution="Q = mcΔT = 0.5 × 4200 × (80-20) = 0.5 × 4200 × 60 = 126000 J = 126 kJ.",
                 tags=["neet", "ncert_direct", "specific_heat"]),
            dict(subtopic="Latent Heat", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Latent heat of fusion of ice is 80 cal/g. Heat required to melt 10 g of ice at 0°C is:",
                 options=["800 cal", "80 cal", "8 cal", "8000 cal"],
                 answer="A",
                 solution="Q = mL = 10 × 80 = 800 cal.",
                 tags=["neet", "ncert_direct", "latent_heat"]),
            dict(subtopic="Conduction Convection Radiation", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Stefan's law states that radiated power P ∝:",
                 options=["T", "T²", "T³", "T⁴"],
                 answer="D",
                 solution="Stefan-Boltzmann law: P = σAT⁴. Power radiated is proportional to T⁴.",
                 tags=["neet", "stefan_boltzmann"]),
        ]
    },

    ("Physics", "Thermodynamics"): {
        "subtopics": ["Zeroth First Second Laws", "Carnot", "Heat Engines"],
        "questions": [
            dict(subtopic="Zeroth First Second Laws", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="First law of thermodynamics is based on conservation of:",
                 options=["Momentum", "Mass", "Energy", "Angular momentum"],
                 answer="C",
                 solution="First law: ΔU = Q - W. It is the law of conservation of energy applied to thermodynamic systems.",
                 tags=["neet", "ncert_direct", "first_law"]),
            dict(subtopic="Carnot", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Efficiency of Carnot engine with hot reservoir T₁=500K and cold reservoir T₂=300K is:",
                 options=["40%", "60%", "30%", "70%"],
                 answer="A",
                 solution="η = 1 - T₂/T₁ = 1 - 300/500 = 1 - 0.6 = 0.4 = 40%.",
                 tags=["neet", "carnot_efficiency"]),
            dict(subtopic="Zeroth First Second Laws", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="For an isothermal expansion of an ideal gas, which is true?",
                 options=["ΔU = 0, Q = W", "ΔU > 0, Q = 0", "W = 0, ΔU = Q", "Q = 0, W < 0"],
                 answer="A",
                 solution="Isothermal (T constant) → ΔU = 0 for ideal gas. By 1st law: Q = W. Heat absorbed equals work done.",
                 tags=["neet", "isothermal_process"]),
        ]
    },

    ("Physics", "Kinetic Theory"): {
        "subtopics": ["Ideal Gas", "KE of Gas", "Degrees of Freedom"],
        "questions": [
            dict(subtopic="Ideal Gas", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="According to kinetic theory, temperature of a gas is a measure of:",
                 options=["Number of molecules", "Size of molecules", "Average kinetic energy of molecules", "Potential energy"],
                 answer="C",
                 solution="Temperature is proportional to the average translational kinetic energy of gas molecules: KE = (3/2)kT.",
                 tags=["neet", "ncert_direct", "kinetic_theory"]),
            dict(subtopic="Degrees of Freedom", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Degrees of freedom of a diatomic gas at moderate temperatures is:",
                 options=["3", "5", "6", "7"],
                 answer="B",
                 solution="Diatomic gas: 3 translational + 2 rotational = 5 degrees of freedom (vibrational not excited at moderate T).",
                 tags=["neet", "degrees_of_freedom"]),
        ]
    },

    ("Physics", "Oscillations"): {
        "subtopics": ["SHM", "Simple Pendulum", "Spring-Mass"],
        "questions": [
            dict(subtopic="SHM", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="In SHM, when displacement is maximum, the acceleration is:",
                 options=["Zero", "Maximum", "Minimum (negative max)", "Equal to velocity"],
                 answer="B",
                 solution="a = -ω²x. When x is maximum (x=A, amplitude), a = -ω²A is maximum in magnitude.",
                 tags=["neet", "ncert_direct", "shm"]),
            dict(subtopic="Simple Pendulum", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Time period of a simple pendulum of length 1 m (g=10 m/s²) is approximately:",
                 options=["2 s", "1 s", "π s", "2π s"],
                 answer="A",
                 solution="T = 2π√(L/g) = 2π√(1/10) = 2π/√10 ≈ 2π/3.16 ≈ 2 s.",
                 tags=["neet", "ncert_direct", "simple_pendulum"]),
            dict(subtopic="Spring-Mass", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Spring constant of a spring is k = 100 N/m. Time period of a 1 kg mass attached to it is:",
                 options=["2π/10 s", "π/5 s", "π/√10 s", "2π/√100 s"],
                 answer="A",
                 solution="T = 2π√(m/k) = 2π√(1/100) = 2π/10 s.",
                 tags=["neet", "spring_mass"]),
        ]
    },

    ("Physics", "Waves"): {
        "subtopics": ["Wave Equation", "Superposition", "Standing Waves", "Doppler"],
        "questions": [
            dict(subtopic="Wave Equation", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Wave speed v, frequency f, and wavelength λ are related by:",
                 options=["v = f + λ", "v = fλ", "f = vλ", "λ = vf"],
                 answer="B",
                 solution="v = fλ. Wave speed equals frequency times wavelength.",
                 tags=["neet", "ncert_direct", "wave_speed"]),
            dict(subtopic="Doppler", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="An ambulance moves toward a stationary observer at 72 km/h. If horn frequency is 1000 Hz (v_sound = 340 m/s), observed frequency is approximately:",
                 options=["1000 Hz", "1069 Hz", "940 Hz", "1200 Hz"],
                 answer="B",
                 solution="v_s = 72 km/h = 20 m/s. f' = f(v/(v-vs)) = 1000(340/320) = 1062.5 ≈ 1069 Hz.",
                 tags=["neet", "doppler_effect"]),
            dict(subtopic="Standing Waves", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="In a standing wave, nodes are points of:",
                 options=["Maximum displacement", "Zero displacement", "Maximum pressure variation", "Maximum velocity"],
                 answer="B",
                 solution="Nodes are points of zero displacement in a standing wave. Antinodes have maximum displacement.",
                 tags=["neet", "standing_waves"]),
        ]
    },

    ("Physics", "Electric Charges & Fields"): {
        "subtopics": ["Coulomb's Law", "Electric Field", "Dipole", "Gauss's Law"],
        "questions": [
            dict(subtopic="Coulomb's Law", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Force between two 1 C charges at 1 m apart in vacuum is: (k=9×10⁹ N·m²/C²)",
                 options=["9×10⁹ N", "1 N", "9 N", "9×10⁶ N"],
                 answer="A",
                 solution="F = kq₁q₂/r² = 9×10⁹×1×1/1² = 9×10⁹ N.",
                 tags=["neet", "ncert_direct", "coulombs_law"]),
            dict(subtopic="Electric Field", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Electric field due to a point charge q at distance r is E = kq/r². If r is doubled, E becomes:",
                 options=["E/2", "2E", "E/4", "4E"],
                 answer="C",
                 solution="E ∝ 1/r². If r→2r, E → E/4. Field decreases by factor 4.",
                 tags=["neet", "ncert_direct", "electric_field"]),
            dict(subtopic="Gauss's Law", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Electric flux through a closed surface enclosing charge Q in vacuum is:",
                 options=["Q/ε₀", "Q·ε₀", "Q/4πε₀", "4πQ/ε₀"],
                 answer="A",
                 solution="Gauss's law: ∮E·dA = Q/ε₀. Electric flux = Q_enclosed/ε₀.",
                 tags=["neet", "gauss_law"]),
        ]
    },

    ("Physics", "Electrostatic Potential & Capacitance"): {
        "subtopics": ["Electric Potential", "Capacitors", "Energy Stored"],
        "questions": [
            dict(subtopic="Electric Potential", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Electric potential at distance r from a charge q is V = kq/r. Work done to bring a charge q₀ from infinity to distance r is:",
                 options=["kqq₀/r", "-kqq₀/r", "kq/r", "zero"],
                 answer="A",
                 solution="Work = q₀ × (V at r - V at ∞) = q₀ × kq/r = kqq₀/r.",
                 tags=["neet", "ncert_direct", "electric_potential"]),
            dict(subtopic="Capacitors", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Two capacitors C₁=3μF and C₂=6μF are in parallel. Equivalent capacitance is:",
                 options=["2μF", "9μF", "18μF", "0.5μF"],
                 answer="B",
                 solution="C_eq (parallel) = C₁+C₂ = 3+6 = 9μF.",
                 tags=["neet", "capacitors_parallel"]),
        ]
    },

    ("Physics", "Current Electricity"): {
        "subtopics": ["Ohm's Law", "Kirchhoff's Laws", "Heating Effect"],
        "questions": [
            dict(subtopic="Ohm's Law", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="A resistance of 5Ω carries a current of 2A. Voltage across it is:",
                 options=["2.5 V", "10 V", "7 V", "0.4 V"],
                 answer="B",
                 solution="V = IR = 2×5 = 10 V.",
                 tags=["neet", "ncert_direct", "ohms_law"]),
            dict(subtopic="Heating Effect", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Power dissipated in a resistor R with current I is:",
                 options=["IR", "I²R", "IR²", "I/R"],
                 answer="B",
                 solution="P = I²R (Joule's law of heating). Also P = V²/R = VI.",
                 tags=["neet", "ncert_direct", "joule_heating"]),
            dict(subtopic="Kirchhoff's Laws", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Kirchhoff's current law (KCL) states that at any junction in a circuit:",
                 options=["Voltage is constant", "Sum of currents entering equals sum leaving", "Resistance is zero", "Power is conserved"],
                 answer="B",
                 solution="KCL: ΣI = 0 at any junction. Sum of currents entering = Sum of currents leaving. Based on charge conservation.",
                 tags=["neet", "ncert_direct", "kcl"]),
        ]
    },

    ("Physics", "Moving Charges & Magnetism"): {
        "subtopics": ["Biot-Savart", "Ampere's Law", "Magnetic Force"],
        "questions": [
            dict(subtopic="Magnetic Force", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Force on a charge q moving with velocity v in magnetic field B is F=qvBsinθ. When θ=90°, F =",
                 options=["0", "qvB", "qvB/2", "2qvB"],
                 answer="B",
                 solution="F = qvB sinθ. At θ=90°, sinθ=1. F = qvB (maximum force).",
                 tags=["neet", "ncert_direct", "magnetic_force"]),
            dict(subtopic="Biot-Savart", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Magnetic field at the centre of a circular loop of radius R carrying current I is:",
                 options=["μ₀I/2R", "μ₀I/4πR", "μ₀I/2πR", "μ₀I/R"],
                 answer="A",
                 solution="B = μ₀I/(2R) at the centre of a circular current loop.",
                 tags=["neet", "biot_savart"]),
        ]
    },

    ("Physics", "Magnetism & Matter"): {
        "subtopics": ["Magnetic Materials", "Earth's Magnetism"],
        "questions": [
            dict(subtopic="Magnetic Materials", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="A material strongly attracted by an external magnetic field is called:",
                 options=["Diamagnetic", "Paramagnetic", "Ferromagnetic", "Antiferromagnetic"],
                 answer="C",
                 solution="Ferromagnetic materials (like Fe, Co, Ni) are strongly attracted by external magnetic fields and can be permanently magnetised.",
                 tags=["neet", "ncert_direct", "ferromagnetism"]),
            dict(subtopic="Earth's Magnetism", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The angle of dip at the magnetic poles of Earth is:",
                 options=["0°", "45°", "90°", "180°"],
                 answer="C",
                 solution="At the magnetic poles, the Earth's field is vertical → angle of dip = 90°. At the magnetic equator, angle of dip = 0°.",
                 tags=["neet", "earth_magnetism"]),
        ]
    },

    ("Physics", "Electromagnetic Induction"): {
        "subtopics": ["Faraday's Law", "Lenz's Law", "Inductance"],
        "questions": [
            dict(subtopic="Faraday's Law", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="EMF induced in a coil is given by Faraday's law as e =",
                 options=["ΔΦ/Δt", "-N(ΔΦ/Δt)", "NΔΦ×Δt", "N/ΔΦ"],
                 answer="B",
                 solution="By Faraday's law: e = -N(dΦ/dt). The negative sign is due to Lenz's law.",
                 tags=["neet", "ncert_direct", "faradays_law"]),
            dict(subtopic="Lenz's Law", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Lenz's law is a consequence of conservation of:",
                 options=["Charge", "Mass", "Energy", "Momentum"],
                 answer="C",
                 solution="Lenz's law ensures that the induced current opposes the cause (change in flux), which is equivalent to energy conservation — the source must do work to drive current.",
                 tags=["neet", "lenz_law"]),
        ]
    },

    ("Physics", "Alternating Current"): {
        "subtopics": ["RMS Values", "LCR Circuits", "Power Factor"],
        "questions": [
            dict(subtopic="RMS Values", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="RMS value of AC voltage v = V₀sinωt is:",
                 options=["V₀", "V₀/2", "V₀/√2", "√2·V₀"],
                 answer="C",
                 solution="V_rms = V₀/√2. For sinusoidal AC, RMS = peak/√2.",
                 tags=["neet", "ncert_direct", "rms_ac"]),
            dict(subtopic="LCR Circuits", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="At resonance in an LCR series circuit, impedance equals:",
                 options=["0", "R", "X_L", "X_C"],
                 answer="B",
                 solution="At resonance X_L = X_C, so they cancel. Z = √(R² + (X_L-X_C)²) = √(R²+0) = R.",
                 tags=["neet", "lcr_resonance"]),
        ]
    },

    ("Physics", "Electromagnetic Waves"): {
        "subtopics": ["EM Spectrum", "Wave Properties"],
        "questions": [
            dict(subtopic="EM Spectrum", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Which electromagnetic wave has the highest frequency?",
                 options=["Radio waves", "Microwaves", "X-rays", "Gamma rays"],
                 answer="D",
                 solution="Order of EM spectrum by increasing frequency: Radio < Microwave < IR < Visible < UV < X-ray < Gamma. Gamma rays have highest frequency.",
                 tags=["neet", "ncert_direct", "em_spectrum"]),
            dict(subtopic="Wave Properties", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Speed of electromagnetic waves in vacuum is:",
                 options=["3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁶ m/s", "Depends on frequency"],
                 answer="A",
                 solution="All EM waves travel at c = 3×10⁸ m/s in vacuum, regardless of frequency.",
                 tags=["neet", "ncert_direct", "speed_of_light"]),
        ]
    },

    ("Physics", "Ray Optics"): {
        "subtopics": ["Mirror Formula", "Lens Formula", "Refraction", "Prism"],
        "questions": [
            dict(subtopic="Mirror Formula", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Mirror formula is 1/v + 1/u = 1/f. Object is 20 cm in front of concave mirror with f=10 cm. Image distance v =",
                 options=["-20 cm", "+20 cm", "10 cm", "-10 cm"],
                 answer="A",
                 solution="u=-20 cm, f=-10 cm (concave mirror, sign convention). 1/v = 1/f - 1/u = -1/10 -(-1/20) = -1/10+1/20 = -1/20. v = -20 cm.",
                 tags=["neet", "mirror_formula"]),
            dict(subtopic="Lens Formula", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="A convex lens has focal length 20 cm. Power of the lens is:",
                 options=["5 D", "+5 D", "-5 D", "0.05 D"],
                 answer="B",
                 solution="P = 1/f(in metres) = 1/0.20 = +5 D. (Positive for convex lens)",
                 tags=["neet", "lens_power"]),
            dict(subtopic="Refraction", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Critical angle for glass-air interface where n_glass = 1.5 is:",
                 options=["sin⁻¹(2/3)", "sin⁻¹(3/2)", "45°", "30°"],
                 answer="A",
                 solution="sin(C) = 1/n = 1/1.5 = 2/3. C = sin⁻¹(2/3) ≈ 41.8°.",
                 tags=["neet", "critical_angle", "tir"]),
        ]
    },

    ("Physics", "Wave Optics"): {
        "subtopics": ["YDSE", "Diffraction", "Polarization"],
        "questions": [
            dict(subtopic="YDSE", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="In YDSE, fringe width β = Dλ/d. If wavelength doubles, fringe width:",
                 options=["Halves", "Doubles", "Stays same", "Quadruples"],
                 answer="B",
                 solution="β = Dλ/d. β ∝ λ. If λ→2λ, then β→2β (fringe width doubles).",
                 tags=["neet", "ncert_direct", "ydse"]),
            dict(subtopic="Polarization", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Which of the following proves transverse nature of light?",
                 options=["Refraction", "Diffraction", "Polarization", "Dispersion"],
                 answer="C",
                 solution="Polarization can only occur in transverse waves (vibration perpendicular to propagation). This proves light is transverse in nature.",
                 tags=["neet", "polarization_transverse"]),
        ]
    },

    ("Physics", "Dual Nature of Radiation & Matter"): {
        "subtopics": ["Photoelectric Effect", "de Broglie"],
        "questions": [
            dict(subtopic="Photoelectric Effect", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Photoelectric effect proves that light behaves as:",
                 options=["A wave", "A particle (photon)", "Both wave and particle simultaneously", "A magnetic wave"],
                 answer="B",
                 solution="Photoelectric effect (Einstein, 1905) demonstrates the particle nature of light. Photons hit electrons and eject them from metal surface.",
                 tags=["neet", "ncert_direct", "photoelectric"]),
            dict(subtopic="Photoelectric Effect", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Threshold frequency ν₀ for a metal is 6×10¹⁴ Hz. Work function φ is: (h=6.63×10⁻³⁴ J·s)",
                 options=["3.98×10⁻¹⁹ J", "6.63×10⁻³⁴ J", "1×10⁻¹⁹ J", "2.5 eV"],
                 answer="A",
                 solution="φ = hν₀ = 6.63×10⁻³⁴ × 6×10¹⁴ = 3.978×10⁻¹⁹ J ≈ 3.98×10⁻¹⁹ J.",
                 tags=["neet", "work_function"]),
        ]
    },

    ("Physics", "Atoms"): {
        "subtopics": ["Bohr Model", "Spectral Series"],
        "questions": [
            dict(subtopic="Bohr Model", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="In Bohr's atomic model, the electron revolves in discrete circular orbits because:",
                 options=["Electromagnetic force is balanced", "Angular momentum is quantised (mvr = nh/2π)", "Coulombic attraction is zero", "Centrifugal force is zero"],
                 answer="B",
                 solution="Bohr's postulate: electrons can only orbit at radii where angular momentum L = mvr = nh/2π, where n is a positive integer.",
                 tags=["neet", "ncert_direct", "bohr_model"]),
            dict(subtopic="Spectral Series", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Lyman series of hydrogen spectrum is emitted when electron transitions to:",
                 options=["n=1 from higher levels", "n=2 from higher levels", "n=3 from higher levels", "n=∞ from higher levels"],
                 answer="A",
                 solution="Lyman series: transitions to n=1 (ground state). In UV region. Balmer series: to n=2 (visible). Paschen: to n=3 (IR).",
                 tags=["neet", "lyman_series"]),
        ]
    },

    ("Physics", "Nuclei"): {
        "subtopics": ["Nuclear Binding Energy", "Radioactivity", "Nuclear Reactions"],
        "questions": [
            dict(subtopic="Radioactivity", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="In alpha decay, the mass number A and atomic number Z of the daughter nucleus are:",
                 options=["A-4, Z-2", "A+4, Z+2", "A-2, Z-4", "A, Z-2"],
                 answer="A",
                 solution="Alpha particle is ⁴₂He. Parent ᴬ_Z X → ᴬ⁻⁴_{Z-2}Y + ⁴₂He. A decreases by 4, Z decreases by 2.",
                 tags=["neet", "ncert_direct", "alpha_decay"]),
            dict(subtopic="Nuclear Binding Energy", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Mass defect of a nucleus is defined as:",
                 options=["Mass of nucleus", "Sum of nucleon masses - mass of nucleus", "Mass of electrons", "Mass of protons only"],
                 answer="B",
                 solution="Mass defect Δm = (Zmp + (A-Z)mn) - M_nucleus. It represents the 'missing' mass converted to binding energy via E=mc².",
                 tags=["neet", "mass_defect"]),
        ]
    },

    ("Physics", "Semiconductor Electronics"): {
        "subtopics": ["p-n Junction", "Transistor", "Logic Gates"],
        "questions": [
            dict(subtopic="p-n Junction", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="A p-n junction diode in forward bias:",
                 options=["Has high resistance", "Allows current to flow easily", "Acts as open circuit", "Acts as capacitor"],
                 answer="B",
                 solution="In forward bias (p-side positive), the depletion region narrows and current flows easily. In reverse bias, the depletion region widens and very little current flows.",
                 tags=["neet", "ncert_direct", "pn_junction"]),
            dict(subtopic="Logic Gates", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Output of NAND gate is 0 only when:",
                 options=["Both inputs are 0", "Both inputs are 1", "One input is 0", "One input is 1"],
                 answer="B",
                 solution="NAND gate truth table: Y = NOT(A·B). Output = 0 only when both A=1 AND B=1. For all other inputs, output = 1.",
                 tags=["neet", "ncert_direct", "logic_gates"]),
            dict(subtopic="Transistor", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="In a common emitter transistor configuration, if α = 0.96, then β =",
                 options=["24", "0.96", "1.04", "96"],
                 answer="A",
                 solution="β = α/(1-α) = 0.96/0.04 = 24.",
                 tags=["neet", "transistor_beta"]),
        ]
    },

    ("Physics", "Communication Systems"): {
        "subtopics": ["Modulation", "Propagation of Waves"],
        "questions": [
            dict(subtopic="Modulation", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Modulation is the process of:",
                 options=["Amplifying signal", "Superimposing message signal on carrier wave", "Removing noise from signal", "Converting digital to analog"],
                 answer="B",
                 solution="Modulation: the process of superimposing a message (low-frequency) signal on a high-frequency carrier wave to enable long-distance transmission.",
                 tags=["neet", "ncert_direct", "modulation"]),
            dict(subtopic="Propagation of Waves", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Sky wave propagation is used for frequencies in the range:",
                 options=["< 2 MHz", "2-30 MHz", "> 30 MHz", "> 300 MHz"],
                 answer="B",
                 solution="Sky waves (reflected by ionosphere) are used for long-range radio communication in the HF band (2-30 MHz = shortwave).",
                 tags=["neet", "sky_wave"]),
        ]
    },
}

# ═══════════════════════════════════════════════════════════════════════════════
#  NEET CHEMISTRY BANK
# ═══════════════════════════════════════════════════════════════════════════════
NEET_CHEMISTRY_BANK = {

    ("Chemistry", "Some Basic Concepts of Chemistry"): {
        "subtopics": ["Mole Concept", "Stoichiometry", "Empirical Formula"],
        "questions": [
            dict(subtopic="Mole Concept", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Avogadro's number (Nₐ) is equal to:",
                 options=["6.022×10²² mol⁻¹", "6.022×10²³ mol⁻¹", "6.022×10²⁴ mol⁻¹", "6.022×10²⁰ mol⁻¹"],
                 answer="B",
                 solution="Avogadro's number Nₐ = 6.022×10²³ mol⁻¹. It represents number of entities in 1 mole.",
                 tags=["neet", "ncert_direct", "avogadro"]),
            dict(subtopic="Mole Concept", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Molar mass of water (H₂O) is:",
                 options=["16 g/mol", "18 g/mol", "2 g/mol", "20 g/mol"],
                 answer="B",
                 solution="M(H₂O) = 2×1 + 16 = 18 g/mol.",
                 tags=["neet", "ncert_direct", "molar_mass"]),
            dict(subtopic="Stoichiometry", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="In the reaction 2H₂ + O₂ → 2H₂O, how many moles of O₂ are needed to form 4 mol H₂O?",
                 options=["4", "2", "1", "8"],
                 answer="B",
                 solution="From equation: 1 mol O₂ → 2 mol H₂O. For 4 mol H₂O: 2 mol O₂ needed.",
                 tags=["neet", "stoichiometry"]),
        ]
    },

    ("Chemistry", "Structure of Atom"): {
        "subtopics": ["Bohr Model", "Electronic Configuration", "Quantum Numbers"],
        "questions": [
            dict(subtopic="Electronic Configuration", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Electronic configuration of Ne (Z=10) is:",
                 options=["2,8", "2,6", "2,7,1", "2,8,2"],
                 answer="A",
                 solution="Ne: 1s² 2s² 2p⁶. Shell distribution: 2,8.",
                 tags=["neet", "ncert_direct", "electronic_configuration"]),
            dict(subtopic="Bohr Model", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Ionisation energy of hydrogen atom from n=1 is 13.6 eV. IE from n=2 is:",
                 options=["13.6 eV", "3.4 eV", "6.8 eV", "27.2 eV"],
                 answer="B",
                 solution="E_n = -13.6/n² eV. From n=2, energy = -13.6/4 = -3.4 eV. IE = 3.4 eV.",
                 tags=["neet", "bohr_model"]),
        ]
    },

    ("Chemistry", "Classification of Elements & Periodicity"): {
        "subtopics": ["Periodic Trends", "Ionisation Energy"],
        "questions": [
            dict(subtopic="Periodic Trends", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Metallic character increases as we go:",
                 options=["Left to right in a period", "Right to left in a period and up in a group", "Down in a group", "Down in a group and right to left in a period"],
                 answer="D",
                 solution="Metallic character increases down a group (larger atoms, easier to lose electrons) and from right to left in a period (lower IE).",
                 tags=["neet", "ncert_direct", "metallic_character"]),
            dict(subtopic="Ionisation Energy", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="First ionisation energy is highest for:",
                 options=["Na", "Mg", "Al", "Si"],
                 answer="B",
                 solution="Mg has stable 3s² configuration (half-filled s subshell). IE: Na (496) < Mg (738) > Al (577) < Si (786) kJ/mol. So Mg > Na and Mg > Al in this period.",
                 tags=["neet", "ionisation_energy"]),
        ]
    },

    ("Chemistry", "Chemical Bonding & Molecular Structure"): {
        "subtopics": ["VSEPR", "Hybridisation", "Bond Polarity"],
        "questions": [
            dict(subtopic="VSEPR", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Shape of NH₃ is:",
                 options=["Trigonal planar", "Pyramidal (trigonal pyramidal)", "Linear", "Tetrahedral"],
                 answer="B",
                 solution="NH₃: N has 3 bonding pairs + 1 lone pair = 4 electron pairs (sp³). Shape is trigonal pyramidal (lone pair not included in shape).",
                 tags=["neet", "ncert_direct", "vsepr"]),
            dict(subtopic="Bond Polarity", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Which molecule has the highest dipole moment?",
                 options=["CO₂", "BF₃", "H₂O", "CCl₄"],
                 answer="C",
                 solution="CO₂ (linear), BF₃ (trigonal planar), CCl₄ (tetrahedral) are all symmetric with zero dipole moment. H₂O is V-shaped (bent) with a net dipole moment (~1.85 D).",
                 tags=["neet", "dipole_moment"]),
        ]
    },

    ("Chemistry", "States of Matter"): {
        "subtopics": ["Gas Laws", "Ideal Gas"],
        "questions": [
            dict(subtopic="Gas Laws", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="At constant volume, if temperature of gas doubles, pressure:",
                 options=["Halves", "Doubles", "Stays same", "Quadruples"],
                 answer="B",
                 solution="Gay-Lussac's Law: P∝T at constant V. If T doubles (in Kelvin), P doubles.",
                 tags=["neet", "ncert_direct", "gay_lussac_law"]),
        ]
    },

    ("Chemistry", "Thermodynamics"): {
        "subtopics": ["Enthalpy", "Gibbs Energy"],
        "questions": [
            dict(subtopic="Gibbs Energy", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="A spontaneous process has:",
                 options=["ΔG > 0", "ΔG = 0", "ΔG < 0", "ΔH < 0 always"],
                 answer="C",
                 solution="Gibbs free energy: ΔG = ΔH - TΔS. For spontaneous process at constant T and P: ΔG < 0.",
                 tags=["neet", "ncert_direct", "spontaneity"]),
        ]
    },

    ("Chemistry", "Equilibrium"): {
        "subtopics": ["Kc Kp", "Acid-Base", "Buffer"],
        "questions": [
            dict(subtopic="Acid-Base", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="According to Bronsted-Lowry theory, an acid is:",
                 options=["Electron pair donor", "Proton donor", "Proton acceptor", "OH⁻ donor"],
                 answer="B",
                 solution="Brønsted-Lowry acid: proton (H⁺) donor. Base: proton acceptor. This extends Arrhenius theory to non-aqueous solutions.",
                 tags=["neet", "ncert_direct", "bronsted_lowry"]),
        ]
    },

    ("Chemistry", "Redox Reactions"): {
        "subtopics": ["Oxidation State"],
        "questions": [
            dict(subtopic="Oxidation State", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Oxidation state of S in H₂SO₄ is:",
                 options=["+4", "+6", "+2", "-2"],
                 answer="B",
                 solution="H₂SO₄: 2H(+1) + S(x) + 4O(-2) = 0 → 2+x-8=0 → x=+6.",
                 tags=["neet", "ncert_direct", "oxidation_state"]),
        ]
    },

    ("Chemistry", "Hydrogen"): {
        "subtopics": ["H2O2", "Water"],
        "questions": [
            dict(subtopic="H2O2", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="H₂O₂ can act as both oxidising and reducing agent because:",
                 options=["It contains oxygen in -1 state (can go to -2 or 0)", "It is acidic", "It is a peroxide", "Both A and C"],
                 answer="D",
                 solution="H₂O₂ has O in -1 state. It can be reduced (-1→-2, oxidising agent) or oxidised (-1→0, reducing agent). Being a peroxide also identifies this property. A and C are both valid reasons.",
                 tags=["neet", "h2o2_redox"]),
        ]
    },

    ("Chemistry", "s-Block Elements"): {
        "subtopics": ["Alkali Metals", "Alkaline Earth Metals"],
        "questions": [
            dict(subtopic="Alkali Metals", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Which alkali metal is used in photoelectric cells because of its low ionisation energy?",
                 options=["Li", "Na", "K", "Cs"],
                 answer="D",
                 solution="Cs has the lowest ionisation energy among alkali metals (and all elements). Its low work function makes it suitable for photoelectric cells.",
                 tags=["neet", "ncert_direct", "caesium"]),
        ]
    },

    ("Chemistry", "p-Block Elements"): {
        "subtopics": ["Group 13-18"],
        "questions": [
            dict(subtopic="Group 13-18", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Which gas is responsible for the green colour of chlorine?",
                 options=["Cl₂", "HCl", "Cl₂ (yellowish-green)", "CCl₄"],
                 answer="C",
                 solution="Cl₂ gas is yellowish-green in colour at room temperature. It has a characteristic pungent, suffocating smell.",
                 tags=["neet", "ncert_direct", "chlorine"]),
            dict(subtopic="Group 13-18", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Ozone (O₃) differs from oxygen (O₂) in that ozone:",
                 options=["Is a different element", "Is an allotrope of oxygen with one more O atom", "Has higher stability", "Supports combustion"],
                 answer="B",
                 solution="Ozone is an allotrope of oxygen — same element (O) in a different molecular form (O₃ vs O₂). Ozone is less stable than O₂ and is a powerful oxidising agent.",
                 tags=["neet", "ozone_allotrope"]),
        ]
    },

    ("Chemistry", "d and f Block Elements"): {
        "subtopics": ["Transition Metals"],
        "questions": [
            dict(subtopic="Transition Metals", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Colour of transition metal compounds is due to:",
                 options=["Large size", "d-d electronic transitions in partially filled d-orbitals", "High melting point", "Variable oxidation states only"],
                 answer="B",
                 solution="Transition metal ions with partially filled d-orbitals absorb visible light to promote electrons between d-orbitals (d-d transitions), making the ions coloured.",
                 tags=["neet", "ncert_direct", "colour_transition"]),
        ]
    },

    ("Chemistry", "Coordination Compounds"): {
        "subtopics": ["IUPAC", "Isomerism"],
        "questions": [
            dict(subtopic="IUPAC", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.74,
                 q_type="single_correct",
                 text="IUPAC name of K₂[PtCl₄] is:",
                 options=["Potassium tetrachloroplatinate(II)", "Dipotassium tetrachloroplatinum", "Potassium chloroplatinate", "Platinum(II) potassium chloride"],
                 answer="A",
                 solution="K₂[PtCl₄]: outer sphere K⁺ (potassium), complex ion [PtCl₄]²⁻ with 4Cl⁻ (tetrachloro) and Pt²⁺ (platinate(II)). Name: Potassium tetrachloroplatinate(II).",
                 tags=["neet", "iupac_coordination"]),
        ]
    },

    ("Chemistry", "Haloalkanes & Haloarenes"): {
        "subtopics": ["SN1 SN2", "Reactions"],
        "questions": [
            dict(subtopic="Reactions", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="Which reagent converts primary alkyl halide to primary alcohol?",
                 options=["KOH/alcohol", "NaOH (aqueous)", "NaCN", "Mg/ether"],
                 answer="B",
                 solution="RX + NaOH(aq) → ROH + NaX. Aqueous NaOH (nucleophilic substitution with OH⁻) converts alkyl halide to alcohol.",
                 tags=["neet", "ncert_direct", "hydrolysis"]),
        ]
    },

    ("Chemistry", "Alcohols, Phenols & Ethers"): {
        "subtopics": ["Properties"],
        "questions": [
            dict(subtopic="Properties", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Victor Meyer's test distinguishes between:",
                 options=["Alcohol and ether", "Primary, secondary, and tertiary alcohols", "Aldehyde and ketone", "Alkane and alkene"],
                 answer="B",
                 solution="Victor Meyer's test distinguishes 1°, 2°, and 3° alcohols. 1°=red (nitrosoamine→red with KOH), 2°=blue (nitroso→blue with KOH), 3°=colourless.",
                 tags=["neet", "victor_meyer"]),
        ]
    },

    ("Chemistry", "Aldehydes, Ketones & Carboxylic Acids"): {
        "subtopics": ["Tests", "Reactions"],
        "questions": [
            dict(subtopic="Tests", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Which test distinguishes aldehyde from ketone?",
                 options=["Lucas test", "Fehling's test", "Victor Meyer's test", "Iodoform test"],
                 answer="B",
                 solution="Fehling's test: aldehydes reduce Cu²⁺ (blue) to Cu₂O (brick red precipitate). Ketones do not reduce Fehling's solution (most ketones).",
                 tags=["neet", "ncert_direct", "fehling_test"]),
        ]
    },

    ("Chemistry", "Amines"): {
        "subtopics": ["Basicity", "Reactions"],
        "questions": [
            dict(subtopic="Reactions", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="The product of reaction between methyl amine and HCl is:",
                 options=["Methylamine hydrochloride", "Chloromethane + NH₃", "Dimethylamine", "NaCl"],
                 answer="A",
                 solution="CH₃NH₂ + HCl → CH₃NH₃⁺Cl⁻ (methylamine hydrochloride / methylammonium chloride). Amines are basic and react with acids to form salts.",
                 tags=["neet", "ncert_direct", "amine_salt"]),
        ]
    },

    ("Chemistry", "Biomolecules"): {
        "subtopics": ["Carbohydrates", "Proteins"],
        "questions": [
            dict(subtopic="Carbohydrates", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Which of the following is a reducing sugar?",
                 options=["Sucrose", "Starch", "Glucose", "Cellulose"],
                 answer="C",
                 solution="Glucose is a reducing sugar (has free aldehyde group). Sucrose is a non-reducing disaccharide (no free anomeric OH). Starch and cellulose are non-reducing polysaccharides.",
                 tags=["neet", "ncert_direct", "reducing_sugar"]),
            dict(subtopic="Proteins", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The secondary structure of proteins involves:",
                 options=["Amino acid sequence", "α-helix and β-pleated sheet (H-bond)", "Disulfide bridges", "Active site interactions"],
                 answer="B",
                 solution="Secondary structure: the local 3D shape of the polypeptide backbone maintained by hydrogen bonding — forming α-helices and β-pleated sheets.",
                 tags=["neet", "protein_structure"]),
        ]
    },

    ("Chemistry", "Polymers"): {
        "subtopics": ["Types of Polymers"],
        "questions": [
            dict(subtopic="Types of Polymers", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Natural rubber is a polymer of:",
                 options=["Styrene", "Isoprene (2-methylbuta-1,3-diene)", "Propylene", "Vinyl chloride"],
                 answer="B",
                 solution="Natural rubber = cis-1,4-polyisoprene. Monomer = isoprene (CH₂=C(CH₃)-CH=CH₂). The repeating unit is derived from isoprene.",
                 tags=["neet", "ncert_direct", "natural_rubber"]),
        ]
    },

    ("Chemistry", "Chemistry in Everyday Life"): {
        "subtopics": ["Medicines", "Food Chemicals"],
        "questions": [
            dict(subtopic="Medicines", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Aspirin (acetylsalicylic acid) is an example of which type of drug?",
                 options=["Antibiotic", "Analgesic-antipyretic", "Antacid", "Sedative"],
                 answer="B",
                 solution="Aspirin is an analgesic (pain relief), antipyretic (fever reduction), and anti-inflammatory drug. It is a non-narcotic analgesic.",
                 tags=["neet", "ncert_direct", "aspirin"]),
            dict(subtopic="Food Chemicals", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Which class of drugs inhibit the enzyme acetylcholinesterase?",
                 options=["Antihistamines", "Antacids", "Organophosphate pesticides/nerve agents", "Penicillins"],
                 answer="C",
                 solution="Organophosphate compounds (some insecticides like malathion, nerve agents) inhibit acetylcholinesterase, preventing breakdown of acetylcholine at nerve synapses.",
                 tags=["neet", "enzyme_inhibitor"]),
        ]
    },
}
