# NEET Biology Question Bank — Production Grade
# Botany (Plant Biology): ~300 questions across 16 chapters
# Zoology (Animal Biology): ~280 questions across 15 chapters

# ═══════════════════════════════════════════════════════════════════════════════
#  NEET BIOLOGY — BOTANY (PLANT SCIENCE)
# ═══════════════════════════════════════════════════════════════════════════════
NEET_BOTANY_BANK = {

    ("Biology", "The Living World"): {
        "subtopics": ["Biodiversity", "Classification", "Taxonomy", "Nomenclature"],
        "questions": [
            dict(subtopic="Taxonomy", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Who gave the binomial nomenclature system?",
                 options=["Charles Darwin", "Carl Linnaeus", "R.H. Whittaker", "Ernst Haeckel"],
                 answer="B",
                 solution="Carl Linnaeus (1753) introduced the binomial nomenclature system — two-part names for species consisting of genus and specific epithet.",
                 tags=["neet", "ncert_direct", "binomial_nomenclature"]),
            dict(subtopic="Classification", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Five kingdom classification was given by:",
                 options=["Linnaeus", "R.H. Whittaker", "Haeckel", "Copeland"],
                 answer="B",
                 solution="R.H. Whittaker (1969) proposed the five kingdom classification: Monera, Protista, Fungi, Plantae, Animalia.",
                 tags=["neet", "ncert_direct", "five_kingdom"]),
            dict(subtopic="Biodiversity", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Species is a group of:",
                 options=["Similar genera", "Interbreeding natural population producing fertile offspring", "All organisms in an area", "Similar families"],
                 answer="B",
                 solution="Biological species concept (Ernst Mayr): a species is a group of actually or potentially interbreeding natural populations that are reproductively isolated from other such groups.",
                 tags=["neet", "ncert_direct", "species_concept"]),
            dict(subtopic="Nomenclature", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Correct scientific name of mango is:",
                 options=["Mangifera indica", "Mangifera Indica", "mangifera indica", "MANGIFERA INDICA"],
                 answer="A",
                 solution="ICBN rules: Genus name is capitalised (Mangifera), species epithet is in lowercase (indica). Written in italics or underlined. Full name: Mangifera indica.",
                 tags=["neet", "ncert_direct", "nomenclature"]),
            dict(subtopic="Classification", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The basic unit of classification is:",
                 options=["Genus", "Order", "Family", "Species"],
                 answer="D",
                 solution="Species is the fundamental unit of biological classification (the basic taxon). Hierarchy: Species < Genus < Family < Order < Class < Phylum < Kingdom.",
                 tags=["neet", "taxonomic_hierarchy"]),
        ]
    },

    ("Biology", "Biological Classification"): {
        "subtopics": ["Kingdom Monera", "Kingdom Protista", "Kingdom Fungi", "Kingdom Plantae & Animalia"],
        "questions": [
            dict(subtopic="Kingdom Monera", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Bacteria are placed in kingdom Monera because they are:",
                 options=["Multicellular", "Prokaryotic (no membrane-bound nucleus)", "Photosynthetic only", "All heterotrophic"],
                 answer="B",
                 solution="Kingdom Monera includes all prokaryotes — organisms without membrane-bound nucleus, membrane-bound organelles. Includes bacteria and cyanobacteria.",
                 tags=["neet", "ncert_direct", "monera"]),
            dict(subtopic="Kingdom Fungi", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Cell walls of fungi are made of:",
                 options=["Cellulose", "Chitin", "Peptidoglycan", "Lignin"],
                 answer="B",
                 solution="Fungal cell walls are made of chitin (a nitrogen-containing polysaccharide). Plants have cellulose. Bacteria have peptidoglycan.",
                 tags=["neet", "ncert_direct", "fungi_cell_wall"]),
            dict(subtopic="Kingdom Protista", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.80,
                 q_type="single_correct",
                 text="Amoeba belongs to kingdom:",
                 options=["Monera", "Protista", "Fungi", "Animalia"],
                 answer="B",
                 solution="Amoeba is a eukaryotic, unicellular organism placed in Kingdom Protista. It moves using pseudopodia and engulfs food by phagocytosis.",
                 tags=["neet", "ncert_direct", "protista"]),
            dict(subtopic="Kingdom Monera", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Cyanobacteria are important because they:",
                 options=["Cause diseases", "Fix atmospheric nitrogen and are oxygenic photosynthesizers", "Decompose organic matter", "Are obligate parasites"],
                 answer="B",
                 solution="Cyanobacteria (blue-green algae) are: (1) capable of oxygenic photosynthesis (contributed O₂ to early atmosphere), (2) many can fix atmospheric N₂ (e.g., Anabaena, Nostoc). Important primary producers.",
                 tags=["neet", "cyanobacteria"]),
            dict(subtopic="Kingdom Fungi", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Lichens are symbiotic associations between:",
                 options=["Algae and bacteria", "Fungi and algae/cyanobacteria", "Mosses and bacteria", "Ferns and fungi"],
                 answer="B",
                 solution="Lichens = fungal partner (mycobiont) + photosynthetic partner (phycobiont = algae or cyanobacteria). The fungus provides structure and water, the alga provides food via photosynthesis.",
                 tags=["neet", "lichens_symbiosis"]),
        ]
    },

    ("Biology", "Plant Kingdom"): {
        "subtopics": ["Algae", "Bryophytes", "Pteridophytes", "Gymnosperms", "Angiosperms"],
        "questions": [
            dict(subtopic="Algae", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Agar-agar is obtained from:",
                 options=["Red algae (Rhodophyta)", "Brown algae", "Green algae", "Blue-green algae"],
                 answer="A",
                 solution="Agar is obtained from red algae (Gelidium, Gracilaria). It is used as a culture medium in microbiology.",
                 tags=["neet", "ncert_direct", "agar"]),
            dict(subtopic="Bryophytes", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Bryophytes are called 'Amphibians of Plant Kingdom' because:",
                 options=["They live in water only", "They need water for sexual reproduction but live on land", "They have gills", "They are aquatic and terrestrial animals"],
                 answer="B",
                 solution="Bryophytes (mosses, liverworts) grow on land but require water for fertilisation (sperm swim to egg). Hence called 'amphibians of plant kingdom'.",
                 tags=["neet", "ncert_direct", "bryophytes"]),
            dict(subtopic="Gymnosperms", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Gymnosperms are characterised by:",
                 options=["Enclosed seeds", "Naked seeds (not enclosed in fruit)", "Flowers", "Double fertilisation"],
                 answer="B",
                 solution="Gymnosperms ('naked seed' in Greek) have seeds not enclosed in a fruit. Examples: Pinus, Cycas, Ginkgo. They do not have flowers or fruits.",
                 tags=["neet", "ncert_direct", "gymnosperms"]),
            dict(subtopic="Angiosperms", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Largest phylum in plant kingdom (most species) is:",
                 options=["Bryophyta", "Pteridophyta", "Coniferophyta", "Angiospermae"],
                 answer="D",
                 solution="Angiosperms (flowering plants) are the most diverse and dominant plant group with ~250,000-350,000 species — the largest division of the plant kingdom.",
                 tags=["neet", "ncert_direct", "angiosperms"]),
            dict(subtopic="Pteridophytes", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Pteridophytes were the first land plants to develop:",
                 options=["Seeds", "Flowers", "Vascular tissue (xylem and phloem)", "Roots"],
                 answer="C",
                 solution="Pteridophytes (ferns, Selaginella, Equisetum) were among the first vascular plants. They have true xylem and phloem but no seeds.",
                 tags=["neet", "vascular_plants"]),
        ]
    },

    ("Biology", "Morphology of Flowering Plants"): {
        "subtopics": ["Root", "Stem", "Leaf", "Flower", "Fruit", "Seed"],
        "questions": [
            dict(subtopic="Root", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Tap root system is present in:",
                 options=["Grass", "Wheat", "Mustard", "Maize"],
                 answer="C",
                 solution="Tap root system (primary root persists with lateral branches) is typical of dicots. Mustard is a dicot → tap root. Grass, Wheat, Maize are monocots → fibrous root.",
                 tags=["neet", "ncert_direct", "tap_root"]),
            dict(subtopic="Leaf", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Which of the following is a modified stem?",
                 options=["Carrot", "Sweet potato", "Ginger", "Radish"],
                 answer="C",
                 solution="Ginger (Zingiber officinale) is a rhizome — a modified underground stem. Carrot and Radish are modified roots (taproots). Sweet potato is a modified tuberous root.",
                 tags=["neet", "ncert_direct", "modified_stem"]),
            dict(subtopic="Flower", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="The essential whorls of a flower are:",
                 options=["Calyx and Corolla", "Stamens and Pistil (androecium and gynoecium)", "Petals and Sepals", "Bract and Bracteole"],
                 answer="B",
                 solution="Essential (reproductive) whorls: Androecium (stamens) and Gynoecium (pistil/carpels). Non-essential (accessory) whorls: Calyx (sepals) and Corolla (petals).",
                 tags=["neet", "ncert_direct", "flower_whorls"]),
            dict(subtopic="Fruit", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Mango is which type of fruit?",
                 options=["Berry", "Drupe (stone fruit)", "Aggregate", "Multiple"],
                 answer="B",
                 solution="Mango is a drupe — a fleshy fruit with a hard stone (endocarp enclosing seed). Other drupes: plum, peach, cherry. Berry: tomato, banana.",
                 tags=["neet", "ncert_direct", "fruit_types"]),
            dict(subtopic="Stem", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The stem tendril of Cucurbita is a modification of:",
                 options=["Leaf", "Axillary bud", "Stipule", "Whole shoot"],
                 answer="B",
                 solution="In Cucurbita (pumpkin), stem tendrils are modifications of axillary buds. In Lathyrus, leaf tendrils are modifications of leaflets.",
                 tags=["neet", "tendril_modification"]),
        ]
    },

    ("Biology", "Anatomy of Flowering Plants"): {
        "subtopics": ["Tissue Types", "Root Anatomy", "Stem Anatomy", "Secondary Growth"],
        "questions": [
            dict(subtopic="Tissue Types", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Meristematic tissue is characterised by:",
                 options=["Large vacuoles and thick cell walls", "Thin cell walls, dense cytoplasm, ability to divide", "Dead cells with lignified walls", "Air spaces for gas exchange"],
                 answer="B",
                 solution="Meristematic (dividing) tissue: small cells, thin cellulose walls, dense cytoplasm, prominent nucleus, small/no vacuoles. Continuously divides to produce new cells.",
                 tags=["neet", "ncert_direct", "meristem"]),
            dict(subtopic="Tissue Types", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Which of the following is a dead tissue at maturity?",
                 options=["Collenchyma", "Parenchyma", "Sclerenchyma", "Mesophyll"],
                 answer="C",
                 solution="Sclerenchyma cells are dead at maturity — cell walls heavily thickened with lignin. Provide mechanical support. Examples: fibres and stone cells (sclereids).",
                 tags=["neet", "ncert_direct", "sclerenchyma"]),
            dict(subtopic="Root Anatomy", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Casparian strips in roots are found in:",
                 options=["Epidermis", "Endodermis", "Pericycle", "Cortex"],
                 answer="B",
                 solution="Casparian strips are waterproof (suberin) bands in the radial and transverse walls of endodermis cells. They prevent apoplastic flow of water into the vascular bundle.",
                 tags=["neet", "casparian_strips"]),
            dict(subtopic="Secondary Growth", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Secondary growth in dicot stems is due to activity of:",
                 options=["Apical meristem", "Vascular cambium and cork cambium", "Intercalary meristem", "Ground meristem"],
                 answer="B",
                 solution="Secondary growth: vascular cambium produces secondary xylem (wood) and secondary phloem. Cork cambium (phellogen) produces cork (phellem) replacing epidermis.",
                 tags=["neet", "secondary_growth"]),
        ]
    },

    ("Biology", "Cell: The Unit of Life"): {
        "subtopics": ["Cell Theory", "Prokaryotic Cell", "Eukaryotic Cell", "Organelles"],
        "questions": [
            dict(subtopic="Cell Theory", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Cell theory was proposed by:",
                 options=["Robert Hooke", "Schleiden and Schwann", "Virchow", "Watson and Crick"],
                 answer="B",
                 solution="Cell theory was proposed by Schleiden (1838, plants) and Schwann (1839, animals). Virchow (1855) added 'all cells arise from pre-existing cells' (Omnis cellula e cellula).",
                 tags=["neet", "ncert_direct", "cell_theory"]),
            dict(subtopic="Organelles", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Mitochondria are called 'powerhouse of the cell' because:",
                 options=["They are the largest organelle", "They produce ATP via cellular respiration", "They store energy as glycogen", "They have a double membrane"],
                 answer="B",
                 solution="Mitochondria produce ATP through aerobic respiration (oxidative phosphorylation). ATP is the universal energy currency of the cell.",
                 tags=["neet", "ncert_direct", "mitochondria"]),
            dict(subtopic="Eukaryotic Cell", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Which organelle is absent in animal cells but present in plant cells?",
                 options=["Mitochondria", "Ribosome", "Plastid (chloroplast)", "Endoplasmic reticulum"],
                 answer="C",
                 solution="Plastids (chloroplasts, chromoplasts, leucoplasts) are found only in plant cells. Animals lack plastids. Both have mitochondria, ribosomes, ER.",
                 tags=["neet", "ncert_direct", "plant_vs_animal"]),
            dict(subtopic="Prokaryotic Cell", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Bacterial ribosome (70S) is made of:",
                 options=["50S + 30S subunits", "60S + 40S subunits", "40S + 30S subunits", "80S + 70S"],
                 answer="A",
                 solution="Prokaryotic ribosomes are 70S = 50S (large) + 30S (small) subunits. Eukaryotic ribosomes are 80S = 60S + 40S.",
                 tags=["neet", "ncert_direct", "ribosome"]),
            dict(subtopic="Organelles", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The Golgi apparatus is involved in:",
                 options=["Protein synthesis", "Modification, sorting, and packaging of proteins", "Cellular respiration", "DNA replication"],
                 answer="B",
                 solution="Golgi apparatus (Golgi complex) receives proteins from ER (cis face), modifies them (glycosylation, etc.), sorts, and packages them for secretion or delivery to other organelles (trans face).",
                 tags=["neet", "golgi_function"]),
        ]
    },

    ("Biology", "Biomolecules"): {
        "subtopics": ["Carbohydrates", "Proteins", "Lipids", "Nucleic Acids", "Enzymes"],
        "questions": [
            dict(subtopic="Proteins", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Number of amino acids in all proteins is:",
                 options=["10", "20", "100", "64"],
                 answer="B",
                 solution="All proteins are made from 20 different amino acids (standard amino acids). These are encoded by the genetic code (64 codons, 61 coding + 3 stop).",
                 tags=["neet", "ncert_direct", "amino_acids"]),
            dict(subtopic="Enzymes", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Enzymes are mainly:",
                 options=["Carbohydrates", "Lipids", "Proteins (with some RNA - ribozymes)", "Vitamins"],
                 answer="C",
                 solution="Enzymes are biological catalysts — almost all are proteins. Some RNA molecules also act as catalysts (ribozymes, e.g., RNA splicing).",
                 tags=["neet", "ncert_direct", "enzymes"]),
            dict(subtopic="Nucleic Acids", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="The two strands of DNA are held together by:",
                 options=["Covalent bonds", "Ionic bonds", "Hydrogen bonds between complementary bases", "Van der Waals forces"],
                 answer="C",
                 solution="DNA double helix is stabilised by hydrogen bonds between complementary base pairs (A=T: 2 H-bonds, G≡C: 3 H-bonds) and by base stacking interactions.",
                 tags=["neet", "ncert_direct", "dna_structure"]),
            dict(subtopic="Enzymes", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Km (Michaelis constant) of an enzyme is:",
                 options=["Maximum velocity of reaction", "Substrate concentration at half-maximum velocity", "Enzyme concentration", "Product concentration"],
                 answer="B",
                 solution="Km is the substrate concentration [S] at which the reaction velocity is half of Vmax. Low Km = high affinity for substrate. High Km = low affinity.",
                 tags=["neet", "michaelis_menten"]),
            dict(subtopic="Carbohydrates", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Cellulose differs from starch in that cellulose has:",
                 options=["α-1,4 glycosidic bonds", "β-1,4 glycosidic bonds", "α-1,6 glycosidic bonds", "Both α-1,4 and α-1,6 bonds"],
                 answer="B",
                 solution="Cellulose: β-1,4 glycosidic linkages between glucose units → linear, rigid. Starch: α-1,4 (amylose) and α-1,6 (amylopectin) → coiled/branched, digestible.",
                 tags=["neet", "cellulose_starch"]),
        ]
    },

    ("Biology", "Cell Cycle and Cell Division"): {
        "subtopics": ["Cell Cycle", "Mitosis", "Meiosis"],
        "questions": [
            dict(subtopic="Cell Cycle", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="DNA replication occurs during which phase of cell cycle?",
                 options=["G₁ phase", "S phase (Synthesis phase)", "G₂ phase", "M phase"],
                 answer="B",
                 solution="DNA synthesis (replication) occurs during S phase of interphase. G₁: growth and protein synthesis. G₂: preparation for division. M: mitosis.",
                 tags=["neet", "ncert_direct", "cell_cycle"]),
            dict(subtopic="Mitosis", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="In mitosis, chromosomes align at the equatorial plate during:",
                 options=["Prophase", "Metaphase", "Anaphase", "Telophase"],
                 answer="B",
                 solution="Metaphase: chromosomes align at the metaphase plate (cell equator). The spindle fibres attach to kinetochores. Easiest phase to count chromosomes.",
                 tags=["neet", "ncert_direct", "metaphase"]),
            dict(subtopic="Meiosis", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="Crossing over (recombination) occurs during:",
                 options=["Leptotene", "Zygotene", "Pachytene", "Diplotene"],
                 answer="C",
                 solution="Crossing over occurs during Pachytene (thick thread stage) of prophase I of meiosis. Non-sister chromatids exchange segments at chiasmata.",
                 tags=["neet", "ncert_direct", "crossing_over"]),
            dict(subtopic="Mitosis", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="If a parent cell has 2n=46 chromosomes, the daughter cells after mitosis will have:",
                 options=["23 chromosomes", "46 chromosomes", "92 chromosomes", "69 chromosomes"],
                 answer="B",
                 solution="Mitosis is equational division: each daughter cell receives the same chromosome number as the parent. 2n=46 → 46 chromosomes per daughter cell.",
                 tags=["neet", "mitosis_chromosome_number"]),
            dict(subtopic="Meiosis", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="During which stage of meiosis do bivalents form?",
                 options=["Leptotene", "Zygotene", "Pachytene", "Diplotene"],
                 answer="B",
                 solution="Zygotene (Zygo = together): homologous chromosomes pair (synapsis) to form bivalents (tetrads). This pairing is mediated by synaptonemal complex.",
                 tags=["neet", "bivalent_formation"]),
        ]
    },

    ("Biology", "Transport in Plants"): {
        "subtopics": ["Diffusion", "Osmosis", "Water Potential", "Transpiration", "Mineral Transport"],
        "questions": [
            dict(subtopic="Osmosis", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Osmosis is movement of water from:",
                 options=["High solute to low solute concentration", "Low water potential to high water potential", "High water potential to low water potential", "High pressure to low pressure"],
                 answer="C",
                 solution="Osmosis: movement of water through a selectively permeable membrane from higher water potential (dilute solution) to lower water potential (concentrated solution).",
                 tags=["neet", "ncert_direct", "osmosis"]),
            dict(subtopic="Water Potential", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Water potential (Ψ) of pure water is:",
                 options=["Less than 0", "Greater than 0", "Equal to 0", "Infinite"],
                 answer="C",
                 solution="Water potential of pure water is taken as 0 (reference). Adding solutes lowers water potential (makes it negative). Pressure can increase water potential.",
                 tags=["neet", "ncert_direct", "water_potential"]),
            dict(subtopic="Transpiration", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Stomata open when guard cells become:",
                 options=["Flaccid", "Turgid", "Plasmolysed", "Dead"],
                 answer="B",
                 solution="Guard cells take up water and become turgid → their inner walls (thick) bow outward, pulling the outer thin walls and creating a pore (stomatal opening).",
                 tags=["neet", "stomata_mechanism"]),
            dict(subtopic="Mineral Transport", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Translocation of food materials in plants occurs through:",
                 options=["Xylem", "Phloem", "Cortex", "Epidermis"],
                 answer="B",
                 solution="Phloem translocates food (sugars) from source (leaves) to sink (roots, growing parts). Xylem transports water and minerals from roots to leaves.",
                 tags=["neet", "phloem_translocation"]),
        ]
    },

    ("Biology", "Mineral Nutrition"): {
        "subtopics": ["Essential Minerals", "Deficiency Symptoms", "Nitrogen Fixation"],
        "questions": [
            dict(subtopic="Essential Minerals", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Which of the following is a macronutrient for plants?",
                 options=["Manganese", "Copper", "Molybdenum", "Nitrogen"],
                 answer="D",
                 solution="Macronutrients required in large amounts: C, H, O, N, P, K, Ca, Mg, S. Micronutrients (trace): Fe, Mn, Cu, Zn, Mo, B, Cl, Ni.",
                 tags=["neet", "ncert_direct", "macronutrients"]),
            dict(subtopic="Nitrogen Fixation", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Biological nitrogen fixation is carried out by:",
                 options=["All bacteria", "Only Rhizobium in root nodules", "Nitrogen-fixing organisms (Rhizobium, Azotobacter, Nostoc, etc.)", "Mycorrhizae"],
                 answer="C",
                 solution="N₂ fixation is carried out by: free-living (Azotobacter, Nostoc, Clostridium) and symbiotic (Rhizobium in legume root nodules, Frankia) nitrogen-fixing organisms. Enzyme: nitrogenase.",
                 tags=["neet", "nitrogen_fixation"]),
            dict(subtopic="Deficiency Symptoms", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Chlorosis (yellowing of leaves) is caused by deficiency of:",
                 options=["Phosphorus", "Nitrogen and Magnesium (Mg is part of chlorophyll)", "Calcium", "Potassium"],
                 answer="B",
                 solution="Chlorosis results from deficiency of: N (essential for amino acids/proteins including chlorophyll proteins), Mg (central atom of chlorophyll ring), Fe, S. N and Mg are most common causes.",
                 tags=["neet", "chlorosis_deficiency"]),
        ]
    },

    ("Biology", "Photosynthesis in Higher Plants"): {
        "subtopics": ["Light Reactions", "Calvin Cycle", "C4 Plants", "Photorespiration"],
        "questions": [
            dict(subtopic="Light Reactions", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Photosynthesis takes place in:",
                 options=["Mitochondria", "Nucleus", "Chloroplast (mainly in thylakoid and stroma)", "Ribosome"],
                 answer="C",
                 solution="Light reactions: thylakoid membranes (grana). Dark reactions (Calvin cycle): stroma of chloroplast.",
                 tags=["neet", "ncert_direct", "chloroplast"]),
            dict(subtopic="Light Reactions", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="The oxygen released during photosynthesis comes from:",
                 options=["CO₂", "Water (H₂O)", "Glucose", "Both CO₂ and H₂O"],
                 answer="B",
                 solution="Photolysis of water: 2H₂O → 4H⁺ + 4e⁻ + O₂. The O₂ released in photosynthesis comes entirely from water molecules, as proven by isotope labelling experiments.",
                 tags=["neet", "ncert_direct", "photolysis"]),
            dict(subtopic="Calvin Cycle", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="The first stable product of CO₂ fixation in C₃ plants is:",
                 options=["Oxaloacetate (OAA)", "3-phosphoglycerate (3-PGA)", "Glucose", "RuBP"],
                 answer="B",
                 solution="In C₃ plants, CO₂ + RuBP → 2 molecules of 3-phosphoglycerate (3-PGA, a 3-carbon compound). Enzyme: RuBisCO.",
                 tags=["neet", "ncert_direct", "calvin_cycle"]),
            dict(subtopic="C4 Plants", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="C₄ plants have Kranz anatomy. What is Kranz anatomy?",
                 options=["Bundle sheath cells with few chloroplasts", "Mesophyll and bundle sheath with large chloroplasts arranged around vascular bundle", "Only mesophyll cells with chloroplasts", "Modified root structure"],
                 answer="B",
                 solution="Kranz anatomy: large bundle sheath cells (containing large chloroplasts) arranged concentrically around the vascular bundle, surrounded by mesophyll cells. Allows CO₂ concentration mechanism in C₄ plants.",
                 tags=["neet", "kranz_anatomy"]),
            dict(subtopic="Light Reactions", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="The number of ATP and NADPH produced in non-cyclic photophosphorylation (per 2H₂O split) is:",
                 options=["2 ATP, 2 NADPH", "3 ATP, 2 NADPH", "2 ATP, 1 NADPH", "4 ATP, 2 NADPH"],
                 answer="B",
                 solution="Non-cyclic photophosphorylation (Z-scheme): per 2 water molecules split: 2 NADPH produced, and approximately 3 ATP generated (varies with chemiosmosis). Actually: 2 NADPH + ~2-3 ATP depending on scheme used. Standard NCERT answer: 2 NADPH + 3 ATP roughly.",
                 tags=["neet", "noncyclic_photophosphorylation"]),
        ]
    },

    ("Biology", "Respiration in Plants"): {
        "subtopics": ["Glycolysis", "Kreb's Cycle", "Electron Transport Chain", "Fermentation"],
        "questions": [
            dict(subtopic="Glycolysis", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Glycolysis occurs in the:",
                 options=["Mitochondria", "Nucleus", "Cytoplasm", "Chloroplast"],
                 answer="C",
                 solution="Glycolysis occurs in the cytoplasm (cytosol). It converts glucose (6C) → 2 pyruvate (3C each) producing 2 ATP and 2 NADH.",
                 tags=["neet", "ncert_direct", "glycolysis"]),
            dict(subtopic="Kreb's Cycle", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Kreb's cycle (TCA cycle) occurs in:",
                 options=["Cytoplasm", "Matrix of mitochondria", "Outer membrane of mitochondria", "Nucleus"],
                 answer="B",
                 solution="Kreb's cycle (Citric acid cycle) takes place in the mitochondrial matrix. Acetyl CoA (2C) enters and is oxidised to 2CO₂ per turn.",
                 tags=["neet", "ncert_direct", "krebs_cycle"]),
            dict(subtopic="Electron Transport Chain", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Net ATP yield from complete oxidation of one glucose molecule is approximately:",
                 options=["2 ATP", "8 ATP", "36-38 ATP", "30 ATP"],
                 answer="C",
                 solution="Complete aerobic respiration: Glycolysis (2 ATP) + Pyruvate decarboxylation (0 ATP) + TCA (2 ATP) + ETC (32-34 ATP) ≈ 36-38 ATP total.",
                 tags=["neet", "atp_yield"]),
            dict(subtopic="Fermentation", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Alcoholic fermentation produces:",
                 options=["Lactic acid + CO₂", "Ethanol + CO₂ + 2 ATP", "Pyruvate + 2 ATP", "Glucose + H₂O"],
                 answer="B",
                 solution="Alcoholic fermentation (yeast): Glucose → 2 Pyruvate → 2 Ethanol + 2CO₂. Net ATP = 2 (from glycolysis). Used in bread, wine, beer.",
                 tags=["neet", "ncert_direct", "fermentation"]),
        ]
    },

    ("Biology", "Plant Growth and Development"): {
        "subtopics": ["Plant Growth", "Phytohormones", "Photoperiodism", "Seed Germination"],
        "questions": [
            dict(subtopic="Phytohormones", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Auxin promotes cell elongation. Where is auxin primarily produced?",
                 options=["Root tips", "Shoot apex (apical meristem)", "Leaves", "Lateral buds"],
                 answer="B",
                 solution="Auxin (IAA - Indole Acetic Acid) is primarily synthesised in the shoot apex (apical meristem) and young leaves. It moves downward (basipetally) to promote cell elongation.",
                 tags=["neet", "ncert_direct", "auxin"]),
            dict(subtopic="Phytohormones", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Which phytohormone promotes dormancy?",
                 options=["Auxin", "Cytokinin", "Abscisic Acid (ABA)", "Gibberellin"],
                 answer="C",
                 solution="Abscisic acid (ABA) is the 'stress hormone' that promotes dormancy, seed dormancy, stomatal closure (during drought), and abscission. Often called the 'inhibitor of growth'.",
                 tags=["neet", "ncert_direct", "aba"]),
            dict(subtopic="Photoperiodism", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Short day plants (SDP) flower when:",
                 options=["Day length is longer than critical period", "Night length is longer than critical period (i.e., short day = long night)", "Temperature is high", "CO₂ levels are high"],
                 answer="B",
                 solution="Short day plants actually respond to night length. They require a continuous dark period LONGER than a critical duration. Eg: Chrysanthemum, Xanthium. (Long night = short day = SDP flowers).",
                 tags=["neet", "photoperiodism_sdp"]),
            dict(subtopic="Phytohormones", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="Which of the following promotes cell division and delays senescence?",
                 options=["Auxin", "Gibberellin", "Cytokinin", "Ethylene"],
                 answer="C",
                 solution="Cytokinin promotes cell division (cytokinesis), delays senescence (Richmond-Lang effect), promotes lateral bud growth. First isolated from coconut milk as zeatin.",
                 tags=["neet", "cytokinin_function"]),
        ]
    },

    ("Biology", "Reproduction in Organisms"): {
        "subtopics": ["Asexual Reproduction", "Sexual Reproduction", "Life Span"],
        "questions": [
            dict(subtopic="Asexual Reproduction", difficulty="easy", difficulty_score=0.85, avg_time=45, accuracy=0.82,
                 q_type="single_correct",
                 text="Vegetative propagation of potato is through:",
                 options=["Seeds", "Leaves", "Tubers (modified stems)", "Roots"],
                 answer="C",
                 solution="Potato tubers are modified underground stems with 'eyes' (buds). These develop into new plants through vegetative propagation (asexual reproduction).",
                 tags=["neet", "ncert_direct", "vegetative_propagation"]),
            dict(subtopic="Sexual Reproduction", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Which of these organisms can undergo both asexual and sexual reproduction?",
                 options=["Humans", "Bacteria", "Sponges (Porifera)", "Birds"],
                 answer="C",
                 solution="Sponges (Porifera) can reproduce asexually (budding, fragmentation, gemmule formation) and sexually (by producing gametes). Many lower organisms show both modes.",
                 tags=["neet", "asexual_sexual_reproduction"]),
        ]
    },

    ("Biology", "Sexual Reproduction in Flowering Plants"): {
        "subtopics": ["Flower Structure", "Pollination", "Fertilisation", "Development"],
        "questions": [
            dict(subtopic="Flower Structure", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Microsporogenesis produces:",
                 options=["Megaspores", "Pollen grains (microspores)", "Embryo sac", "Seeds"],
                 answer="B",
                 solution="Microsporogenesis: microspore mother cells (MMC) in anther undergo meiosis to form haploid microspores (pollen grains). Megasporogenesis: in ovule, forms megaspores.",
                 tags=["neet", "ncert_direct", "microsporogenesis"]),
            dict(subtopic="Fertilisation", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Double fertilisation in angiosperms results in:",
                 options=["Two embryos", "Embryo and endosperm", "Two seeds", "Seed and fruit"],
                 answer="B",
                 solution="Double fertilisation (unique to angiosperms): one sperm + egg → zygote → embryo (2n). Second sperm + 2 polar nuclei → endosperm (3n). Discovered by Nawaschin (1898).",
                 tags=["neet", "ncert_direct", "double_fertilisation"]),
            dict(subtopic="Pollination", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Pollination by wind is called:",
                 options=["Entomophily", "Anemophily", "Hydrophily", "Ornithophily"],
                 answer="B",
                 solution="Anemophily = wind pollination. Entomophily = insect pollination. Hydrophily = water pollination. Ornithophily = bird pollination.",
                 tags=["neet", "pollination_types"]),
        ]
    },

    ("Biology", "Principles of Inheritance and Variation"): {
        "subtopics": ["Mendel's Laws", "Dihybrid Cross", "Incomplete Dominance", "Codominance", "Chromosomal Theory"],
        "questions": [
            dict(subtopic="Mendel's Laws", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.82,
                 q_type="single_correct",
                 text="Mendel's Law of Segregation states that:",
                 options=["Characters are blended in offspring", "Two alleles of a gene separate during gamete formation", "All genes segregate independently", "Traits are inherited from one parent only"],
                 answer="B",
                 solution="Law of Segregation (Law of Purity of Gametes): each organism has two alleles for each trait that separate (segregate) during gamete formation, so each gamete carries one allele.",
                 tags=["neet", "ncert_direct", "mendel_segregation"]),
            dict(subtopic="Dihybrid Cross", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Ratio in F₂ of a dihybrid cross (RrYy × RrYy) following Mendel's laws is:",
                 options=["3:1", "1:2:1", "9:3:3:1", "1:1:1:1"],
                 answer="C",
                 solution="Dihybrid cross F₂ ratio = 9:3:3:1 (9 round yellow : 3 round green : 3 wrinkled yellow : 1 wrinkled green). This demonstrates independent assortment.",
                 tags=["neet", "ncert_direct", "dihybrid_ratio"]),
            dict(subtopic="Incomplete Dominance", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="In incomplete dominance, F₁ of RR (red) × WW (white) is pink. F₂ ratio of phenotypes is:",
                 options=["3:1 (red:white)", "1:2:1 (red:pink:white)", "1:1 (pink:white)", "All pink"],
                 answer="B",
                 solution="Incomplete dominance: F₁ = RW (pink, intermediate). F₂ of RW × RW: RR(red):RW(pink):WW(white) = 1:2:1. Both genotype and phenotype ratio = 1:2:1.",
                 tags=["neet", "incomplete_dominance"]),
            dict(subtopic="Chromosomal Theory", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Chromosomal theory of inheritance was proposed by:",
                 options=["Mendel", "Sutton and Boveri", "Morgan", "Darwin"],
                 answer="B",
                 solution="Sutton and Boveri (1902-1903) independently proposed the chromosomal theory of inheritance — that chromosomes are the carriers of Mendel's factors (genes).",
                 tags=["neet", "chromosomal_theory"]),
        ]
    },

    ("Biology", "Molecular Basis of Inheritance"): {
        "subtopics": ["DNA Structure", "Replication", "Transcription", "Translation", "Genetic Code"],
        "questions": [
            dict(subtopic="DNA Structure", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.82,
                 q_type="single_correct",
                 text="The DNA double helix was elucidated by:",
                 options=["Griffith and Avery", "Watson and Crick (1953)", "Meselson and Stahl", "Beadle and Tatum"],
                 answer="B",
                 solution="James Watson and Francis Crick proposed the double helix structure of DNA in 1953, based on X-ray data of Rosalind Franklin and Wilkins, and Chargaff's rules.",
                 tags=["neet", "ncert_direct", "watson_crick"]),
            dict(subtopic="Genetic Code", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The codon AUG codes for which amino acid (also start codon)?",
                 options=["Valine", "Methionine (Met)", "Serine", "Leucine"],
                 answer="B",
                 solution="AUG is the start codon that codes for Methionine (Met). UAA, UAG, UGA are stop codons (nonsense codons). The genetic code is triplet, degenerate, and universal.",
                 tags=["neet", "ncert_direct", "start_codon"]),
            dict(subtopic="Replication", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="DNA replication is:",
                 options=["Conservative", "Semi-conservative (confirmed by Meselson and Stahl)", "Dispersive", "Non-conservative"],
                 answer="B",
                 solution="Meselson-Stahl experiment (1958) confirmed semiconservative replication: each new DNA molecule has one old (parental) strand and one new strand.",
                 tags=["neet", "ncert_direct", "dna_replication"]),
            dict(subtopic="Transcription", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="In transcription, the template strand is:",
                 options=["The coding strand (sense strand)", "The non-coding strand (antisense strand, 3'→5')", "Both strands simultaneously", "RNA strand"],
                 answer="B",
                 solution="RNA polymerase reads the template (antisense/non-coding) strand in 3'→5' direction to synthesise mRNA in 5'→3' direction. The mRNA has same sequence as coding (sense) strand (with U instead of T).",
                 tags=["neet", "transcription_template"]),
            dict(subtopic="Translation", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="If mRNA codon is 5'-AUG-UAU-GGG-UAA-3', the number of amino acids in the polypeptide is:",
                 options=["4", "3", "2", "1"],
                 answer="B",
                 solution="AUG (start, Met) - UAU (Tyr) - GGG (Gly) - UAA (STOP). The stop codon UAA does not code for an amino acid. Polypeptide = Met-Tyr-Gly = 3 amino acids.",
                 tags=["neet", "mrna_translation"]),
        ]
    },

    ("Biology", "Evolution"): {
        "subtopics": ["Origin of Life", "Theories of Evolution", "Natural Selection", "Speciation"],
        "questions": [
            dict(subtopic="Theories of Evolution", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Natural selection theory was proposed by:",
                 options=["Lamarck", "Charles Darwin", "Hugo de Vries", "Weismann"],
                 answer="B",
                 solution="Charles Darwin (1859, 'On the Origin of Species') proposed theory of evolution by natural selection. Alfred Russel Wallace independently proposed similar theory simultaneously.",
                 tags=["neet", "ncert_direct", "darwin"]),
            dict(subtopic="Natural Selection", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Industrial melanism in Biston betularia (peppered moth) is an example of:",
                 options=["Mutation", "Natural selection", "Genetic drift", "Gene flow"],
                 answer="B",
                 solution="Industrial melanism: as pollution darkened tree bark, dark moths had better camouflage and survived better (selected by predators). Classic evidence of natural selection in action.",
                 tags=["neet", "ncert_direct", "natural_selection"]),
            dict(subtopic="Speciation", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Reproductive isolation is essential for:",
                 options=["Genetic recombination", "Speciation (formation of new species)", "Genetic drift", "Migration"],
                 answer="B",
                 solution="Speciation requires reproductive isolation — barriers preventing gene flow between populations. Over time, isolated populations diverge genetically and may become new species.",
                 tags=["neet", "speciation"]),
        ]
    },

    ("Biology", "Human Health and Disease"): {
        "subtopics": ["Pathogens", "Immunity", "Vaccines", "Lifestyle Diseases"],
        "questions": [
            dict(subtopic="Pathogens", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.82,
                 q_type="single_correct",
                 text="Malaria is caused by:",
                 options=["Bacteria", "Virus", "Plasmodium (protozoan)", "Fungus"],
                 answer="C",
                 solution="Malaria is caused by Plasmodium (a protozoan) — P. falciparum, P. vivax, P. malariae, P. ovale. Transmitted by female Anopheles mosquito.",
                 tags=["neet", "ncert_direct", "malaria"]),
            dict(subtopic="Immunity", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Antibodies are produced by:",
                 options=["T lymphocytes", "B lymphocytes (plasma cells)", "Macrophages", "Neutrophils"],
                 answer="B",
                 solution="B lymphocytes (B cells) differentiate into plasma cells upon antigen stimulation. Plasma cells produce antibodies (immunoglobulins) specific to the antigen.",
                 tags=["neet", "ncert_direct", "antibodies"]),
            dict(subtopic="Vaccines", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Active immunity is produced by:",
                 options=["Transfer of antibodies from another organism", "Vaccination or natural infection", "Transfer of activated T cells", "Mother's milk"],
                 answer="B",
                 solution="Active immunity: body produces its own antibodies in response to antigens (vaccination or infection). Passive immunity: pre-formed antibodies transferred (from mother, or injected serum).",
                 tags=["neet", "active_immunity"]),
            dict(subtopic="Pathogens", difficulty="hard", difficulty_score=0.25, avg_time=120, accuracy=0.30,
                 q_type="single_correct",
                 text="HIV attacks which cells of the immune system?",
                 options=["B lymphocytes", "CD4⁺ T-helper lymphocytes", "Macrophages only", "Natural killer cells"],
                 answer="B",
                 solution="HIV (Human Immunodeficiency Virus) specifically infects CD4⁺ T-helper cells (because HIV binds to CD4 receptor + co-receptor CCR5/CXCR4). Destruction of T-helper cells leads to AIDS.",
                 tags=["neet", "hiv_aids"]),
        ]
    },

    ("Biology", "Strategies for Enhancement in Food Production"): {
        "subtopics": ["Plant Breeding", "Animal Husbandry", "Biofortification"],
        "questions": [
            dict(subtopic="Plant Breeding", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Norman Borlaug is known for developing:",
                 options=["Hybrid rice", "High yielding semi-dwarf wheat varieties (Green Revolution)", "Bt cotton", "Golden rice"],
                 answer="B",
                 solution="Norman Borlaug (Nobel Peace Prize, 1970) developed high-yielding, disease-resistant semi-dwarf wheat varieties. Led to the Green Revolution that saved millions from starvation.",
                 tags=["neet", "ncert_direct", "green_revolution"]),
            dict(subtopic="Animal Husbandry", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="MOET (Multiple Ovulation Embryo Transfer) is used to:",
                 options=["Increase meat production", "Produce multiple offspring from a superior female in a short time", "Improve immunity of cattle", "Treat diseases in animals"],
                 answer="B",
                 solution="MOET: hormones induce superovulation (many eggs) in superior female, fertilised in vitro or in vivo, embryos transferred to surrogate mothers → multiple offspring from one superior female quickly.",
                 tags=["neet", "moet"]),
        ]
    },

    ("Biology", "Microbes in Human Welfare"): {
        "subtopics": ["Industrial Uses", "Sewage Treatment", "Biocontrol", "Biofertilizers"],
        "questions": [
            dict(subtopic="Industrial Uses", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Penicillin (antibiotic) is produced by:",
                 options=["Bacteria (Bacillus)", "Fungus Penicillium", "Actinomycetes", "Yeast"],
                 answer="B",
                 solution="Penicillin was discovered by Alexander Fleming (1928) in the mould Penicillium notatum. It is the first antibiotic isolated. Modern production uses Penicillium chrysogenum.",
                 tags=["neet", "ncert_direct", "penicillin"]),
            dict(subtopic="Sewage Treatment", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="During secondary treatment of sewage, the BOD is reduced by:",
                 options=["Physical filtration", "Bacterial aerobic decomposition of organic matter (activated sludge)", "Chlorination", "UV radiation"],
                 answer="B",
                 solution="Secondary (biological) treatment: sewage passed into aeration tanks with activated sludge (bacteria + fungi). Aerobic microbes decompose organic matter → BOD reduced significantly.",
                 tags=["neet", "sewage_treatment"]),
        ]
    },

    ("Biology", "Biotechnology: Principles and Processes"): {
        "subtopics": ["Recombinant DNA", "PCR", "Cloning Vectors", "Gel Electrophoresis"],
        "questions": [
            dict(subtopic="Recombinant DNA", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Restriction enzymes (RE) are also called 'molecular scissors' because they:",
                 options=["Cut proteins", "Cut DNA at specific palindromic sequences", "Ligate DNA fragments", "Replicate DNA"],
                 answer="B",
                 solution="Restriction endonucleases (RE) recognise specific palindromic DNA sequences and cut at or near those sites, creating sticky or blunt ends. Used in rDNA technology.",
                 tags=["neet", "ncert_direct", "restriction_enzymes"]),
            dict(subtopic="PCR", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="PCR (Polymerase Chain Reaction) is used to:",
                 options=["Translate mRNA to protein", "Amplify specific DNA sequences in vitro", "Sequence amino acids", "Perform gel electrophoresis"],
                 answer="B",
                 solution="PCR (Kary Mullis, 1983) amplifies specific DNA sequences in vitro through repeated cycles of: denaturation (94°C) + primer annealing (~55°C) + extension by Taq polymerase (72°C).",
                 tags=["neet", "ncert_direct", "pcr"]),
            dict(subtopic="Gel Electrophoresis", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="In agarose gel electrophoresis, smaller DNA fragments move:",
                 options=["Slower (towards negative electrode)", "Faster (towards positive electrode)", "Toward negative electrode", "Not at all"],
                 answer="B",
                 solution="DNA is negatively charged. In electrophoresis, DNA migrates toward positive electrode. Smaller fragments migrate faster through the gel matrix (sieve effect). Larger fragments are retarded more.",
                 tags=["neet", "gel_electrophoresis"]),
        ]
    },

    ("Biology", "Biotechnology and its Applications"): {
        "subtopics": ["GM Organisms", "Gene Therapy", "ELISA"],
        "questions": [
            dict(subtopic="GM Organisms", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Bt cotton is resistant to insects because of:",
                 options=["Chemical pesticides sprayed", "Cry proteins (δ-endotoxins) from Bacillus thuringiensis gene inserted into cotton", "Natural immunity of cotton", "Thick cuticle"],
                 answer="B",
                 solution="Bt cotton contains the Cry gene from Bacillus thuringiensis. Cry proteins (crystalline insecticidal proteins) are produced in the plant, solubilised in insect gut, and destroy the gut cells of bollworm larvae.",
                 tags=["neet", "ncert_direct", "bt_cotton"]),
            dict(subtopic="Gene Therapy", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The first clinical gene therapy was done for the treatment of:",
                 options=["Diabetes", "ADA deficiency (Adenosine Deaminase deficiency)", "Cancer", "Sickle cell anaemia"],
                 answer="B",
                 solution="The first approved gene therapy (1990) treated SCID due to ADA (adenosine deaminase) deficiency. Functional ADA gene was introduced into T lymphocytes of the patient.",
                 tags=["neet", "ncert_direct", "gene_therapy"]),
        ]
    },

    ("Biology", "Organisms and Populations"): {
        "subtopics": ["Ecology", "Population Attributes", "Population Interactions"],
        "questions": [
            dict(subtopic="Population Attributes", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The 'logistic growth' model of population growth is represented by:",
                 options=["J-shaped curve (exponential)", "S-shaped curve (sigmoid, with K = carrying capacity)", "Linear growth", "Decreasing curve"],
                 answer="B",
                 solution="Logistic growth (Verhulst-Pearl equation): dN/dt = rN(K-N)/K. Results in S-shaped (sigmoid) curve. Population growth slows as it approaches carrying capacity K.",
                 tags=["neet", "ncert_direct", "logistic_growth"]),
            dict(subtopic="Population Interactions", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Commensalism is an interaction where:",
                 options=["Both organisms benefit (+/+)", "One benefits, other is neither harmed nor helped (+/0)", "One benefits at expense of other (+/-)", "Both are harmed (-/-)"],
                 answer="B",
                 solution="Commensalism (+/0): one organism benefits, the other is unaffected. Example: barnacles on whale (barnacles get transport, whale unaffected).",
                 tags=["neet", "ncert_direct", "commensalism"]),
        ]
    },

    ("Biology", "Ecosystem"): {
        "subtopics": ["Energy Flow", "Food Chains", "Nutrient Cycling", "Ecological Pyramids"],
        "questions": [
            dict(subtopic="Energy Flow", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The 10% Law in ecology (Lindemann) states that:",
                 options=["Only 10% of energy is lost as heat", "Only 10% of energy at one trophic level is transferred to the next", "90% of energy is transferred to next level", "Plants convert 10% of sunlight to food"],
                 answer="B",
                 solution="Lindemann's 10% law: only ~10% of energy at one trophic level is available to the next. Rest is used for respiration, lost as heat. This limits the length of food chains.",
                 tags=["neet", "ncert_direct", "10_percent_law"]),
            dict(subtopic="Ecological Pyramids", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Which ecological pyramid is always upright (never inverted)?",
                 options=["Pyramid of numbers", "Pyramid of biomass", "Pyramid of energy", "All can be inverted"],
                 answer="C",
                 solution="Pyramid of energy is always upright because energy is always lost at each trophic level (2nd law of thermodynamics). Pyramids of numbers and biomass can be inverted (e.g., tree ecosystem).",
                 tags=["neet", "ecological_pyramid"]),
        ]
    },

    ("Biology", "Biodiversity and Conservation"): {
        "subtopics": ["Types of Biodiversity", "Biodiversity Hotspots", "Conservation"],
        "questions": [
            dict(subtopic="Biodiversity Hotspots", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Which of the following regions is a biodiversity hotspot in India?",
                 options=["Gangetic Plain", "Deccan Plateau", "Western Ghats & Eastern Himalayas", "Thar Desert"],
                 answer="C",
                 solution="India has 4 biodiversity hotspots: Western Ghats & Sri Lanka, Eastern Himalayas (Indo-Burma), Sundaland (including Nicobar Islands), and Indo-Myanmar.",
                 tags=["neet", "ncert_direct", "biodiversity_hotspot"]),
            dict(subtopic="Conservation", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="In situ conservation of biodiversity means:",
                 options=["Conservation in zoological parks", "Conservation in seed banks", "Conservation in natural habitat (national parks, biosphere reserves)", "Conservation in botanical gardens"],
                 answer="C",
                 solution="In situ (in place) conservation: protecting organisms in their natural habitat. Examples: national parks, wildlife sanctuaries, biosphere reserves. Ex situ: outside natural habitat (zoos, seed banks).",
                 tags=["neet", "ncert_direct", "in_situ_conservation"]),
        ]
    },
}

# ═══════════════════════════════════════════════════════════════════════════════
#  NEET BIOLOGY — ZOOLOGY (ANIMAL SCIENCE)
# ═══════════════════════════════════════════════════════════════════════════════
NEET_ZOOLOGY_BANK = {

    ("Biology", "Animal Kingdom"): {
        "subtopics": ["Classification", "Phylum Porifera", "Phylum Coelenterata", "Phylum Platyhelminthes", "Phylum Nematoda", "Phylum Arthropoda", "Phylum Mollusca", "Phylum Echinodermata", "Phylum Chordata"],
        "questions": [
            dict(subtopic="Classification", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Coelom is a body cavity lined with:",
                 options=["Ectoderm", "Endoderm", "Mesoderm (coelomic epithelium)", "All three layers"],
                 answer="C",
                 solution="A true coelom (eucoelomate) is a body cavity lined by mesoderm (coelomic epithelium). Acoelomate: no coelom. Pseudocoelomate: cavity between mesoderm and endoderm.",
                 tags=["neet", "ncert_direct", "coelom"]),
            dict(subtopic="Phylum Porifera", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Sponges (Porifera) are characterised by:",
                 options=["Radial symmetry and nervous system", "Cellular level of organisation, pores, and choanocytes", "Bilateral symmetry", "Coelomate body plan"],
                 answer="B",
                 solution="Porifera (sponges): cellular level of organisation, body full of pores (ostia), choanocytes (collar cells) for water circulation and feeding. Hermaphrodite, no nervous system.",
                 tags=["neet", "ncert_direct", "porifera"]),
            dict(subtopic="Phylum Arthropoda", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The largest phylum in the animal kingdom is:",
                 options=["Chordata", "Mollusca", "Arthropoda", "Annelida"],
                 answer="C",
                 solution="Arthropoda is the largest phylum (~80% of all known animal species). They have jointed appendages, exoskeleton of chitin, segmented body. Examples: insects, crustaceans, arachnids.",
                 tags=["neet", "ncert_direct", "arthropoda"]),
            dict(subtopic="Phylum Chordata", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="All chordates have three fundamental characters at some stage. Which is NOT a chordate character?",
                 options=["Notochord", "Dorsal hollow nerve cord", "Pharyngeal gill slits", "Ventral solid nerve cord"],
                 answer="D",
                 solution="Chordate characters: notochord, dorsal hollow nerve cord, pharyngeal gill slits, post-anal tail. Non-chordates have a ventral solid nerve cord. Chordates have DORSAL hollow nerve cord.",
                 tags=["neet", "chordate_characters"]),
        ]
    },

    ("Biology", "Structural Organisation in Animals"): {
        "subtopics": ["Animal Tissues", "Organ Systems"],
        "questions": [
            dict(subtopic="Animal Tissues", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Which tissue connects bones to muscles?",
                 options=["Ligament", "Tendon", "Cartilage", "Fibrous connective tissue"],
                 answer="B",
                 solution="Tendon: dense fibrous connective tissue connecting muscle to bone. Ligament: connects bone to bone. Both are made primarily of collagen.",
                 tags=["neet", "ncert_direct", "tendon"]),
            dict(subtopic="Animal Tissues", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Ciliated epithelium is found in:",
                 options=["Skin", "Respiratory tract (trachea, bronchi)", "Blood vessels", "Kidney tubules"],
                 answer="B",
                 solution="Ciliated columnar epithelium lines the respiratory tract. Cilia beat to move mucus and trapped particles upward (mucociliary clearance).",
                 tags=["neet", "ciliated_epithelium"]),
        ]
    },

    ("Biology", "Human Physiology: Digestion and Absorption"): {
        "subtopics": ["GI Tract", "Digestion", "Absorption", "Digestive Enzymes"],
        "questions": [
            dict(subtopic="Digestive Enzymes", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Bile is secreted by the liver and helps in digestion of:",
                 options=["Proteins", "Carbohydrates", "Fats (lipids — bile emulsifies fat)", "Nucleic acids"],
                 answer="C",
                 solution="Bile (secreted by liver, stored in gallbladder) does not contain enzymes. It emulsifies fats (breaks large fat globules into smaller droplets), making them accessible to lipase.",
                 tags=["neet", "ncert_direct", "bile"]),
            dict(subtopic="Digestion", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="The enzyme pepsin is secreted in the stomach and acts on:",
                 options=["Carbohydrates", "Fats", "Proteins (cleaves peptide bonds)", "Nucleic acids"],
                 answer="C",
                 solution="Pepsin is a protease secreted as pepsinogen (inactive) by chief cells in the stomach. Activated by HCl → pepsin. Cleaves proteins into smaller polypeptides at pH 1.5-2.",
                 tags=["neet", "ncert_direct", "pepsin"]),
            dict(subtopic="Absorption", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The site of maximum absorption of digested food in humans is:",
                 options=["Stomach", "Duodenum", "Ileum (small intestine) due to villi and microvilli", "Large intestine"],
                 answer="C",
                 solution="Maximum absorption occurs in the ileum (and jejunum) of the small intestine. Villi and microvilli (brush border) enormously increase the absorptive surface area (~200 m²).",
                 tags=["neet", "ncert_direct", "absorption_ileum"]),
        ]
    },

    ("Biology", "Human Physiology: Breathing and Exchange of Gases"): {
        "subtopics": ["Respiratory Organs", "Mechanics of Breathing", "Transport of Gases"],
        "questions": [
            dict(subtopic="Transport of Gases", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Oxygen is transported in the blood mainly as:",
                 options=["Dissolved in plasma", "Oxyhaemoglobin (HbO₂) in RBCs", "CO₂-Hb compound", "Bicarbonate ions"],
                 answer="B",
                 solution="About 97% of O₂ is transported as oxyhaemoglobin (HbO₂) in red blood cells. Only ~3% is dissolved in plasma.",
                 tags=["neet", "ncert_direct", "oxygen_transport"]),
            dict(subtopic="Mechanics of Breathing", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="During inspiration, the diaphragm:",
                 options=["Relaxes and moves up", "Contracts and moves down, increasing thoracic volume", "Moves upward to compress lungs", "Stays stationary"],
                 answer="B",
                 solution="During inspiration: diaphragm contracts (flattens/moves down) and external intercostals contract (ribs move up and out) → thoracic volume increases → pressure decreases → air flows in.",
                 tags=["neet", "ncert_direct", "inspiration"]),
            dict(subtopic="Transport of Gases", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="CO₂ is transported mainly in blood as:",
                 options=["Oxyhaemoglobin", "Dissolved in plasma only", "Bicarbonate ions (HCO₃⁻) in plasma (~70%)", "Carboxy haemoglobin"],
                 answer="C",
                 solution="CO₂ transport: ~70% as bicarbonate ions (HCO₃⁻) in plasma (chloride shift). ~20-25% as carbaminohaemoglobin (CO₂ + Hb). ~7% dissolved in plasma.",
                 tags=["neet", "co2_transport"]),
        ]
    },

    ("Biology", "Human Physiology: Body Fluids and Circulation"): {
        "subtopics": ["Blood Components", "Heart", "Blood Pressure", "Lymph"],
        "questions": [
            dict(subtopic="Blood Components", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.82,
                 q_type="single_correct",
                 text="Normal blood group A means the person has:",
                 options=["Antigen A and antibody anti-A", "Antigen A and antibody anti-B", "Antigen B and antibody anti-A", "No antigens"],
                 answer="B",
                 solution="Blood group A: has A antigens on RBCs, anti-B antibodies in plasma. Group B: B antigens, anti-A antibodies. Group AB: both antigens, no antibodies. Group O: no antigens, both antibodies.",
                 tags=["neet", "ncert_direct", "blood_groups"]),
            dict(subtopic="Heart", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="The pacemaker of the heart is:",
                 options=["AV node", "Purkinje fibres", "SA node (sinoatrial node)", "Bundle of His"],
                 answer="C",
                 solution="SA node (sinoatrial node) in the right atrium is the pacemaker — generates the impulse for heartbeat (~72 beats/min). The impulse goes: SA node → AV node → Bundle of His → Purkinje fibres → ventricles.",
                 tags=["neet", "ncert_direct", "pacemaker"]),
            dict(subtopic="Heart", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Cardiac output = heart rate × stroke volume. If HR = 72/min and SV = 70 mL, CO is:",
                 options=["7200 mL/min", "5040 mL/min = 5.04 L/min", "142 mL/min", "1 L/min"],
                 answer="B",
                 solution="CO = HR × SV = 72 × 70 = 5040 mL/min = 5.04 L/min (approximately 5 L/min at rest).",
                 tags=["neet", "cardiac_output"]),
        ]
    },

    ("Biology", "Human Physiology: Excretory Products"): {
        "subtopics": ["Kidney Structure", "Urine Formation", "Osmoregulation"],
        "questions": [
            dict(subtopic="Kidney Structure", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The functional unit of the kidney is:",
                 options=["Kidney corpuscle", "Nephron", "Collecting duct", "Loop of Henle"],
                 answer="B",
                 solution="Nephron is the structural and functional unit of the kidney. Each kidney has ~1 million nephrons. Consists of Bowman's capsule (with glomerulus), proximal tubule, loop of Henle, distal tubule.",
                 tags=["neet", "ncert_direct", "nephron"]),
            dict(subtopic="Urine Formation", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Glomerular filtration rate (GFR) in a healthy adult is approximately:",
                 options=["1 mL/min", "125 mL/min (180 L/day)", "1000 mL/min", "50 mL/min"],
                 answer="B",
                 solution="GFR = 125 mL/min = 180 L/day. Of this, 178.5 L is reabsorbed → ~1.5 L urine produced per day. GFR is regulated by the juxtaglomerular apparatus (JGA).",
                 tags=["neet", "ncert_direct", "gfr"]),
        ]
    },

    ("Biology", "Human Physiology: Locomotion and Movement"): {
        "subtopics": ["Skeletal System", "Muscle Contraction", "Joints"],
        "questions": [
            dict(subtopic="Muscle Contraction", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Sliding filament theory of muscle contraction involves:",
                 options=["Actin filaments shortening", "Myosin filaments shortening", "Actin filaments sliding over myosin filaments", "Both actin and myosin shortening"],
                 answer="C",
                 solution="Sliding filament theory (Huxley & Hanson, 1954): muscle contracts when actin (thin filaments) slide over stationary myosin (thick filaments). Neither actin nor myosin changes length.",
                 tags=["neet", "ncert_direct", "sliding_filament"]),
            dict(subtopic="Skeletal System", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Total number of bones in adult human skeleton is:",
                 options=["300", "200", "206", "106"],
                 answer="C",
                 solution="Adult human skeleton has 206 bones. At birth ~300-350 bones (many fuse during development). Axial skeleton (80) + Appendicular skeleton (126) = 206.",
                 tags=["neet", "ncert_direct", "bones_count"]),
        ]
    },

    ("Biology", "Human Physiology: Neural Control and Coordination"): {
        "subtopics": ["Neuron Structure", "Nerve Impulse", "Brain Structure", "Reflex Arc"],
        "questions": [
            dict(subtopic="Neuron Structure", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="The junction between two neurons is called a:",
                 options=["Node of Ranvier", "Synapse", "Axon hillock", "Dendrite"],
                 answer="B",
                 solution="Synapse: the junction (gap) between two neurons or between a neuron and effector. Chemical synapse: neurotransmitters are released from synaptic vesicles into synaptic cleft.",
                 tags=["neet", "ncert_direct", "synapse"]),
            dict(subtopic="Nerve Impulse", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="During the action potential, the neuron membrane first becomes:",
                 options=["Polarised (Na⁺ pumped out)", "Depolarised (Na⁺ rushes in)", "Hyperpolarised", "Impermeable to all ions"],
                 answer="B",
                 solution="Action potential: stimulus → Na⁺ channels open → Na⁺ influx → depolarisation (inside becomes positive). Then K⁺ channels open → K⁺ efflux → repolarisation. Na⁺/K⁺ pump restores resting potential.",
                 tags=["neet", "action_potential"]),
            dict(subtopic="Brain Structure", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="The 'master gland' (pituitary) is controlled by:",
                 options=["Thalamus", "Hypothalamus", "Cerebellum", "Medulla oblongata"],
                 answer="B",
                 solution="The hypothalamus controls the pituitary gland via releasing and inhibiting hormones (e.g., GnRH, TRH, CRH). The pituitary is thus called the 'master gland' but is itself controlled by the hypothalamus.",
                 tags=["neet", "pituitary_hypothalamus"]),
        ]
    },

    ("Biology", "Human Physiology: Chemical Coordination"): {
        "subtopics": ["Endocrine Glands", "Hormones", "Feedback Mechanisms"],
        "questions": [
            dict(subtopic="Hormones", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Insulin is secreted by the pancreas. It acts to:",
                 options=["Increase blood glucose levels", "Decrease blood glucose (promotes glucose uptake)", "Increase glucagon", "Break down glycogen only"],
                 answer="B",
                 solution="Insulin (from β cells of islets of Langerhans): lowers blood glucose by promoting glucose uptake by cells, glycogen synthesis (glycogenesis), and inhibiting gluconeogenesis.",
                 tags=["neet", "ncert_direct", "insulin"]),
            dict(subtopic="Endocrine Glands", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="Thyroid gland secretes thyroxine (T4). Iodine is required because:",
                 options=["Iodine activates tyrosine", "Thyroxine contains 4 iodine atoms per molecule", "Iodine is part of the receptor for thyroxine", "Iodine is a coenzyme"],
                 answer="B",
                 solution="Thyroxine (T4) contains 4 iodine atoms; triiodothyronine (T3) contains 3. Iodine deficiency → goitre. Thyroxine is synthesised from tyrosine + iodine.",
                 tags=["neet", "ncert_direct", "thyroxine_iodine"]),
            dict(subtopic="Feedback Mechanisms", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Negative feedback control of hormone secretion means:",
                 options=["More hormone is released when levels are low (promoting more secretion)", "Rising hormone levels inhibit further secretion by the gland", "Positive feedback loop", "Hormone is never secreted once target is reached"],
                 answer="B",
                 solution="Negative feedback: when hormone levels rise above set point, hypothalamus/pituitary reduce stimulation → gland decreases secretion. Maintains homeostasis. Example: thyroid hormone inhibits TRH and TSH secretion.",
                 tags=["neet", "negative_feedback"]),
        ]
    },

    ("Biology", "Human Reproduction"): {
        "subtopics": ["Male Reproductive System", "Female Reproductive System", "Menstrual Cycle", "Fertilisation", "Development"],
        "questions": [
            dict(subtopic="Male Reproductive System", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Sperm are produced in the:",
                 options=["Epididymis", "Seminal vesicles", "Seminiferous tubules of testes", "Prostate gland"],
                 answer="C",
                 solution="Spermatogenesis occurs in the seminiferous tubules of the testes. Sertoli cells (nurse cells) support sperm development. Leydig cells (interstitial cells) produce testosterone.",
                 tags=["neet", "ncert_direct", "spermatogenesis"]),
            dict(subtopic="Menstrual Cycle", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.78,
                 q_type="single_correct",
                 text="Ovulation (release of egg) in a 28-day cycle typically occurs on day:",
                 options=["Day 1-5", "Day 14", "Day 21-28", "Day 7"],
                 answer="B",
                 solution="Ovulation occurs ~14 days before the next menstruation. In a 28-day cycle: day 14 (luteal phase = 14 days is constant; follicular phase varies).",
                 tags=["neet", "ncert_direct", "ovulation"]),
            dict(subtopic="Fertilisation", difficulty="easy", difficulty_score=0.85, avg_time=55, accuracy=0.76,
                 q_type="single_correct",
                 text="Fertilisation in humans normally occurs in:",
                 options=["Uterus", "Ovary", "Fallopian tube (oviduct)", "Vagina"],
                 answer="C",
                 solution="Fertilisation of the egg by sperm normally occurs in the ampullary-isthmic junction of the fallopian tube (oviduct). The fertilised egg (zygote) then travels to the uterus for implantation.",
                 tags=["neet", "ncert_direct", "fertilisation_site"]),
            dict(subtopic="Development", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Implantation of the blastocyst in the uterus occurs on approximately:",
                 options=["Day 6-7 after fertilisation", "Day 1", "Day 28 (next period)", "Day 14"],
                 answer="A",
                 solution="After fertilisation, the blastocyst (formed after ~4-5 days of cleavage) implants in the endometrium of the uterus around days 6-7 post-fertilisation.",
                 tags=["neet", "implantation"]),
        ]
    },

    ("Biology", "Reproductive Health"): {
        "subtopics": ["Contraception", "STDs", "Infertility", "MTP"],
        "questions": [
            dict(subtopic="Contraception", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Oral contraceptive pills contain:",
                 options=["Progesterone and Oestrogen (prevent ovulation)", "LH and FSH", "GnRH", "HCG"],
                 answer="A",
                 solution="Combined oral contraceptive pills contain synthetic progesterone + oestrogen. They prevent ovulation by inhibiting FSH and LH secretion (negative feedback on hypothalamus/pituitary).",
                 tags=["neet", "ncert_direct", "oral_contraceptives"]),
            dict(subtopic="STDs", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="The causative agent of syphilis is:",
                 options=["Neisseria gonorrhoeae", "Treponema pallidum (bacterium)", "HIV", "Chlamydia trachomatis"],
                 answer="B",
                 solution="Syphilis is caused by Treponema pallidum (a spirochaete bacterium). Gonorrhoea: Neisseria gonorrhoeae. Chlamydia: Chlamydia trachomatis. All are STDs (sexually transmitted diseases).",
                 tags=["neet", "syphilis_causative"]),
        ]
    },

    ("Biology", "Genetics: Inheritance and Variation"): {
        "subtopics": ["Sex Determination", "Linked Genes", "Mutations"],
        "questions": [
            dict(subtopic="Sex Determination", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="In humans, sex is determined by the:",
                 options=["Mother's X chromosome", "Father's sex chromosome (X or Y)", "Number of autosomes", "Environmental factors"],
                 answer="B",
                 solution="Human females are XX, males are XY. Mother always gives X. Father gives either X (daughter) or Y (son). So the father's contribution determines the sex of offspring.",
                 tags=["neet", "ncert_direct", "sex_determination"]),
            dict(subtopic="Linked Genes", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.52,
                 q_type="single_correct",
                 text="Colour blindness in humans is an X-linked recessive trait. A colour-blind father and carrier mother can have:",
                 options=["Only colour-blind sons", "50% colour-blind sons and 50% normal sons", "Colour-blind daughters only", "No colour-blind offspring"],
                 answer="B",
                 solution="Father: X^b Y. Mother (carrier): X^B X^b. Cross: X^B X^b × X^b Y. Sons: X^B Y (normal) and X^b Y (colour blind) = 50% colour-blind sons. Daughters: X^B X^b (carrier) and X^b X^b (colour blind) = 50% colour-blind daughters.",
                 tags=["neet", "x_linked_inheritance"]),
        ]
    },

    ("Biology", "Molecular Basis of Inheritance"): {
        "subtopics": ["DNA Fingerprinting", "Mutations"],
        "questions": [
            dict(subtopic="DNA Fingerprinting", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.78,
                 q_type="single_correct",
                 text="DNA fingerprinting uses:",
                 options=["Unique coding sequences", "VNTRs (Variable Number of Tandem Repeats) / microsatellites", "Mitochondrial DNA only", "rRNA genes"],
                 answer="B",
                 solution="DNA fingerprinting (Alec Jeffreys, 1984) uses VNTRs (minisatellites/microsatellites) — short repeated sequences that are highly variable between individuals. Used in forensics, paternity testing.",
                 tags=["neet", "ncert_direct", "dna_fingerprinting"]),
        ]
    },

    ("Biology", "Human Health and Disease"): {
        "subtopics": ["Cancer", "Drugs and Alcohol", "Immune System"],
        "questions": [
            dict(subtopic="Cancer", difficulty="easy", difficulty_score=0.85, avg_time=50, accuracy=0.80,
                 q_type="single_correct",
                 text="Cancer cells are characterised by:",
                 options=["Contact inhibition and controlled division", "Loss of contact inhibition and uncontrolled division", "Programmed cell death", "Normal cell cycle"],
                 answer="B",
                 solution="Cancer cells: uncontrolled proliferation, loss of contact inhibition (don't stop dividing when touching other cells), immortalisation, invasion, metastasis (spread). Caused by mutations in proto-oncogenes or tumour suppressors.",
                 tags=["neet", "ncert_direct", "cancer"]),
            dict(subtopic="Drugs and Alcohol", difficulty="medium", difficulty_score=0.50, avg_time=90, accuracy=0.55,
                 q_type="single_correct",
                 text="Heroin is derived from:",
                 options=["Cannabis", "Morphine (from opium poppy) by acetylation", "Cocaine (from coca leaves)", "LSD from ergot fungus"],
                 answer="B",
                 solution="Heroin (diacetylmorphine) is produced by acetylation of morphine, which is an opiate from opium poppy (Papaver somniferum). Heroin is a highly addictive opioid analgesic.",
                 tags=["neet", "ncert_direct", "heroin"]),
        ]
    },
}
